criteria.md
My first attempt at reformatting and rewording some of the criteria in the OSS Project Basics.  The intent is to try and make the criteria easy to identify by placing them on separate lines or by breaking down lists.  Where possible I've also separated information about testing, future releases and rationale from the criteria.
I haven't changed too much of the content.  Let me know if this type of change is something the project is interested in - if so I'll continue through the rest of the Basic Criteria.
=> Updating OSS Project Basics

background.md
Now that I've read the [Markdown style guide](http://www.cirosantilli.com/markdown-style-guide/), I've updated the text to reflect the earlier pull requests around 80 columns vs paragraphs vs single sentences on a line.
=> Updated Markdown text

criteria.md
A few minor changes/suggestions for the Change Control section.
Tried to move the positive form of the criteria first (e.g., MUST) to start of the sentence, followed by the negative form (e.g., MUST NOT) - this is to counter the common view that security just says 'no'.
Changed 'such as' to e.g.'s, and changed 'feature request' in the basic documentation section to align with the Bug-reporting section.
As always happy for thoughts and suggestions.
=> Change control update

other.md
Added further suggestions to include a requirement for a project to:
1. to issue vulnerability advisories
1. sign executable binaries
=> Vuln advisories and signing binaries

doc/criteria.md
In the introductory section of the criteria page, add some material to
the second paragraph to indicate that a project's social health should
be considered a goal, in addition to purely technical outcomes,
because sustained technical success for an open source project is much
more likely with a functional community.
=> In criteria intro, note community health as a goal

doc/criteria.md
This fixes the link from Readme.md.
=> Rename crypto_oss to crypto_floss

Gemfile, Gemfile.lock, lib/tasks/default.rake
@david-a-wheeler 
```bash
$ rake eslint
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```
This was causing a failure in Heroku deploys with these errors:
```bash
remote:        Bundle completed (0.48s)
remote:        Cleaning up the bundler cache.
remote: sh: 2: Syntax error: Unterminated quoted string
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: cannot load such file -- eslintrb/eslinttask
```
=> Use fork of eslintrb to avoid error

test/fixtures/projects.yml
the badge_status field populated via YAML.
#303 quick fix
=> Noticed that the displayed badge (which is computed) doesn't match

app/views/projects/index.html.erb, db/migrate/20160501143232_add_badge_status_to_projects.rb, db/migrate/20160503195329_add_stats_extension.rb, db/schema.rb, lib/tasks/default.rake
@david-a-wheeler @dwvisser 
I believe the problems on master were caused by invalid data that caused the migration https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/db/migrate/20160501143232_add_badge_status_to_projects.rb#L7 to fail.
Specifically, when I run `rake pull_master` I get:
```bash
g_restore: setting owner and privileges for INDEX "public.index_users_on_uid"
pg_restore: setting owner and privileges for INDEX "public.index_versions_on_item_type_and_item_id"
pg_restore: setting owner and privileges for INDEX "public.unique_schema_migrations"
pg_restore: setting owner and privileges for FK CONSTRAINT "public.fk_rails_b872a6760a"
== 20160501143232 AddBadgeStatusToProjects: migrating =========================
-- add_column(:projects, :badge_status, :string)
-> …
```
=> Dan 310 pull database

app/models/concerns/string_refinements.rb, app/models/project.rb, app/validators/url_validator.rb, test/models/concerns/string_refinements.rb
These changes are mainly just stylistic but seem more readable to me.
URL validator is changing to match https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/app/models/project.rb#L95
=> Minor refactor

app/helpers/application_helper.rb, app/helpers/projects_helper.rb, app/views/projects/_form.html.erb, app/views/projects/_status_chooser.html.erb, app/views/projects/_table.html.erb, test/helpers/projects_helper_test.rb
@david-a-wheeler This fixes #332 and also cleans up the markdown helper to be a regular instance method of ProjectHelper rather than a class method of ApplicationHelper.
=> Clickable URLs

app/assets/javascripts/project-form.js, app/models/project.rb, test/models/project_test.rb
The client and server need to agree on what's required to
have a URL in a justification.  Otherwise the subtle difference
could produce confusing results in rare cases.  Also, add tests for them.
=> Make contains URL functions match between client and server

app/views/projects/feed.atom.builder
@david-a-wheeler 
Looking at https://master.bestpractices.coreinfrastructure.org/feed it was clear there's no need to truncate description.
=> No need to truncate descriptions in RSS

app/views/users/index.html.erb, app/views/users/show.html.erb, test/integration/admin_users_show_test.rb
This will make it easier for admins to provide focused feedback
to specific users.
=> Allow admins to easily send email to users

circle.yml, lib/tasks/default.rake
@david-a-wheeler As discussed, this adds pulling the production database to staging when we deploy master to staging. Also, I make the license finder report available in the Artifacts tab on CircleCI.
=> Update rake task

criteria.yml
The current "static_analysis" "description" is long (171 words) and no "details" exists.
This moves hides most "description" content in a corresponding "details" paragraph.
=> Split description and details of "static_analysis"

app/views/projects/_table.html.erb
The W3C validator noted that these img references did not have
an 'alt' value for accessibility.  Fix that.
This partly addresses issue #390.
=> In /projects list add 'alt' tag to img for accessibility

criteria.yml
The current "crypto_random" "description" includes technical details which are implied for the proficient reader.
This hides the technical details in a dedicated "details" paragraph.
=> Split description and details of "crypto_random"

lib/tasks/default.rake
There's no need to confirm when we're overwriting the staging database
with production; we *want* staging to be as similar as possible
to production.  This commit automatically confirms the overwrite.
=> Automatically confirm overwriting staging with production

app/views/layouts/_footer.html.erb
Add to the footer a link to the issue tracker.
That way, if users have problems anywhere on the site,
there's information on the page explaning what to do next.
=> Modify footer layout to clarify what to do for help

test/fixtures/projects.yml
Dan Kohn's workaround for test failures causes an unusual
dependency on projects.yml.  Document that.
=> Add comment to fixture warning of unusual interdependency

install-badge-dev-env
These changes were necessary but not sufficient. Only the first line of `add-pkg` libraries are getting included, so no cmake or postgres. See the following log of an install on my new Mac:
```
$ ./install-badge-dev-env 
install-badge-dev-env: Auto-install development environment for BadgeApp.
See INSTALL.md for more information.
STAGE 1: Determine the package manager to use.
Will use the installer command 'brew install'
STAGE 2: Identifying and install system packages
About to install system packages with the command:
brew install  phantomjs rbenv ruby-build
==> Installing dependencies for phantomjs: openssl
==> Installing phantomjs dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz …
```
=> install updates

app/views/projects/_form.html.erb, app/views/projects/_table.html.erb
This will slightly discourage people from trying to create
nonsense badge entries to increase their search engine rankings,
by marking repo and project URLs as 'nofollow'.
For more information on nofollow, see:
https://en.wikipedia.org/wiki/Nofollow
By itself this commit doesn't do anything with generated markdown;
so far that hasn't been a problem.
=> Add rel=nofollow for repo and project URLs. Fixes #422

app/assets/stylesheets/application.css
This change will fix extra space at the top of the page caused by the previous header fix.
=> This fixes extra spacing at the top of the page on small screens

app/views/project_stats/index.html.erb
Add a 7-day average to the new/updated project chart, and
add a link to the JSON data.  This is per request from CII.
=> Improve project_stats display (7-day average, JSON link). Fixes #441

lib/tasks/default.rake
We continue to have tests intermittently fail (see issue #397).
This commit is a work-around that forces test seeds to be one of
a few specific values. This should eliminate many test failures
until a more permanent fix is found.
=> Fix test seed to eliminate intermittent test failures.

app/controllers/users_controller.rb, test/integration/users_signup_test.rb
This fixes issue #515. I created a new method redirect_existing because I was getting an Metrics/ABCsize offense for create if I had the conditional statements in the new method contained within create.
=> Redirect activated user to login if they try to sign up. Fixes issue #515

app/helpers/projects_helper.rb, app/views/projects/_table.html.erb
We've been able to sort projects for a while, and that's
been useful internally. This commit makes it easy to invoke a
sort order from the user interface of /projects.
=> Add a web UI for sorting projects, fixes #459

Gemfile, Gemfile.lock, lib/tasks/default.rake, test/features/github_login_test.rb, test/test_helper.rb
This fixes issue #397.  I implemented DatabaseCleaner in order to fix the intermittent test issues.  The issue was that the database wasn't being cleaned up after runs using capybara.  Database cleaner is a little slower (~30%), but reliable tests are more important than speedy ones.
=> Fix issues with testing suite, particularly failures with some seeds 

test/capybara_feature_test.rb, test/controllers/users_controller_test.rb, test/features/access_home_test.rb, test/features/filter_test.rb, test/features/github_login_test.rb, test/features/login_test.rb, test/helpers/sessions_helper_test.rb, test/integration/admin_users_show_test.rb, test/integration/feed_test.rb, test/integration/password_resets_test.rb, test/integration/project_list_test.rb, test/integration/users_edit_test.rb, test/integration/users_index_test.rb, test/integration/users_login_test.rb, test/integration/users_manipulate_project_test.rb, test/integration/users_signup_test.rb, test/models/project_stat_test.rb, test/models/project_test.rb, test/models/user_test.rb, test/test_helper.rb, test/unit/lib/blank_detective_test.rb, test/unit/lib/build_detective_test.rb, test/unit/lib/chief_test.rb, test/unit/lib/floss_license_detective_test.rb, test/unit/lib/github_basic_detective_test.rb, test/unit/lib/name_from_url_detective_test.rb
This takes test speed performance back on par with what it was before the seeding issue was fixed.  Instead of running database cleaner between each test, we now only run it for tests which involve Capybara.  
This did produce an issue when running feed_test.rb since it reloads the database at a fixed time and thus muddies the time stamps in the database. This was fixed by turning off use_transactional_fixtures for that test only.    
I also did a little bit of test cleanup so we now make callbacks to setup rather than overwriting the setup method when our tests need special setup features.
=> Speed up tests by only using DatabaseCleaner for Capybara tests

app/views/projects/_form.html.erb
Hi there! This is a very minor fix, but I noted a mistake when beginning to fill out the identification form. 
Question 4 is missing a "be".
=> Fix minor syntax error on identification form

app/views/project_stats/index.json.jbuilder, app/views/projects/_form.html.erb
Make it easier to fill in the (first) implementation language by
providing a datalist.  These are the top 100 languages according to
TIOBE in December 2016: http://www.tiobe.com/tiobe-index/
This only helps with the *first* one - datalists aren't designed to
handle embedded lists - but that's enough to be a minor assist.
=> Provide a datalist for implementation languages (to simplify input)

README.md
- Use https
- Switch badge style from flat-square to default (to match other badges)
=> MIT License badge style

install-badge-dev-env
The gem rugged requires pkg-config to be installed.  Not all Ubuntu flavors have this package installed by default (Xubuntu, for example) so we should make sure it gets installed.
=> Add pkg-config to required packages for Ubuntu flavors.

app/controllers/static_pages_controller.rb, app/views/static_pages/error_404.html, app/views/static_pages/error_404.html.erb
This fixes errors with the 404 page when a format other than html was requested.  #604 
=> Fixes for 404 pages to ignore formats

app/views/projects/_form.html.erb, config/routes.rb
This resolves #632. 
I had to adjust the routes a bit, but got it to work.  
http://stackoverflow.com/questions/4707471/render-template-and-change-url-string-in-browser was quite helpful. 
=> Preserve edit in url on failed edit

app/views/projects/new.html.erb
These attributes are ruby/bootstrap but the validater sees them as bad HTML. I tried removing them and it seem to make no change. I think they were not needed and are just boilerplate.
=> Removed hide_label attributes the were not valid HTML

app/controllers/sessions_controller.rb, app/helpers/sessions_helper.rb, test/features/login_test.rb
When a user logs in from a page other than the root url of the site, lets redirect them back to where they were.  Also redirect logged in users back to the root_url if they try to get /login.
This fixes Issue #635
=> Redirect to previous url on login

app/controllers/projects_controller.rb, app/helpers/sessions_helper.rb, test/features/github_login_test.rb
If a user clicked the "Big green button" (Get your badge now) and were not signed in, they would be asked to login but then redirected back to the homepage. This makes it so they are redirected back to projects/new after logging in.
=> Redirect back to projects/new after signin from projects/new

app/models/project.rb, app/views/projects/_form.html.erb, app/views/projects/index.json.jbuilder, app/views/projects/show.json.jbuilder
Clearly indicate that all badge entries from now on are CC-BY-3.0+.
Copyright would probably be limited on badge entry data anyway,
but we want to encourage people to see and use this data, so having
a clear common license for the badge entry data is helpful.
We could have chosen CC0 (essentially public domain), which would be
easier for later users because no attribution would be needed.
However, attribution might encourage people to provide data
(and incentivize them to enter *correct* data).
All other non-code information in the badge project is also CC-BY-3.0+,
so this is consistent.
We only indicate this license if there's an updated_at after a date;
this is so the license is only shown if the user has accepted it
(as indicated selecting save or submit just under text declaring …
=> Indicate badge entry data is licensed as CC-BY-3.0+ from now on

app/views/layouts/_footer.html.erb, app/views/projects/_form.html.erb, app/views/projects/_status_chooser.html.erb
BootStrap doesn't like nested rows. This was throwing a ton of errors because it was in the status-chooser. I tested it a number of ways and just removing the row class from this part of the form seems to work.
=> Matt boot strap rows in rows fix

app/views/projects/_form.html.erb
Cache almost the entire project entry when showing it.
We don't cache the entry on edit, because it's about to change
(and is thus pointless).
Local testing shows an 80% increase in speed in the server-side
completion time when displaying project entries for read (after the
first display).
We could cache smaller fragments of the project entry for editing,
but it's not clear it's worth it (at this time).
=> Cache almost entire project entry when showing it (is_disabled==true)

README.md
One of these badges is not like the others. It's references elsewhere, so I'd prefer to remove here, since it's not providing any status info about the project.
=> Remove changelog badge

doc/other.md
The first dash char is Unicode U+2014, not the normal dash.
The second quotation marks are U+201C and U+201D. 
Is it done intentionally?
=> Replaced some strange punctuation

.gitignore, Gemfile, Gemfile.lock, doc/dependency_decisions.yml, test/test_helper.rb
This produces additional test output, including a list of the slowest tests and an HTML artifact, when run as `SLOW=1 rails t` or on CI.
=> Dan minitest reporter

config/routes.rb
This is a response to New Relic [showing](https://rpm.newrelic.com/accounts/1653316/applications/48884059/filterable_errors?tw%5Bdur%5D=last_30_minutes&tw%5Bend%5D=1496925078#/show/999ac4f2-4c44-11e7-a209-0242ac110010_0_12288/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&_k=9orgy9) >5% error rates this morning at the URL `/kk.php` with:
```bash
I18n::InvalidLocale: "kk" is not a valid locale
/app/app/controllers/application_controller.rb:   75:in `set_locale'
```
=> Blackhole kk.php robot attacks

app/views/projects/new.html.erb, config/locales/en.yml
This is pure guesswork in terms of syntax. Although OR is a short word, no reason to keep it untranslated, especially since it is in the largest font in the middle of the project creation page.
=> Add "OR" on the project creation page as a snippet to translate

Gemfile
Reduce the gems loaded, particularly in the production environment.
This speeds booting and can reduce memory use.
We don't need gem 'faker' at all in production, so explicitly
state that we only load it during test or development.
In many other cases we can add 'require: false' to disable bundler's
automatic loading.
=> Reduce gems loaded

db/migrate/20170608192851_make_many_not_null.rb, db/schema.rb, doc/implementation.md, test/models/user_test.rb
This prevents some data problems, since even if the application
has a bug, the database will prevent certain invalid values.
For unknown status values we use '?' and set it as the default,
instead of using "null" to indicate unknown values.
That way, the value displayed to the user in English
is exactly the same as what we store.
=> Modify many database fields to be "not null"

app/models/project.rb, app/views/shared/_error_messages.html.erb, config/locales/en.yml
One thing that this does not fix is the "error/errors", which requires
a different solution that the current one with "pluralize" which works
for English, but would not work in other languages.
Also, I'm not sure at all about the allowed scope/syntax for these named
strings, so the patch might be completely wrong. At least it shows what
I'm trying to do. :-)
=> Tentative to internationalize the error messages for wrong forms

Gemfile, config/boot.rb
Bootsnap can speed startup by using caches. However, we can't use it in:
* testing, because it makes test coverage results wrong
* production, because we regenerate things on restart (so it doesn't help)
* fake_production, because we want fake_production to be maximally
similar to production.
So, use it only in development.
=> Only run bootsnap in development

.rubocop.yml, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/lib/floss_license_detective.rb, app/lib/subdir_file_contents_detective.rb, app/models/project.rb, app/models/project_stat.rb, app/models/user.rb, app/validators/email_validator.rb, lib/tasks/default.rake, test/controllers/projects_controller_test.rb
A number of cops are [disabled](https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml) by default. This PR turns on all cops by default and then explicitly disables the ones that are too annoying, such as forbidding inline comments. This both found additional improvements now and will enable new disabled cops by default in future versions.
Note that calling private `send` is appropriate for testing private methods but should not need to be used in regular code.
For posterity, here was the report of all violations that the current .rubocop.yml found:
```bash
Offenses:
app/controllers/projects_controller.rb:173:14: C: Rails/SaveBang: Use destroy! instead of destroy if the return value is not checked. …
```
=> Default all Rubocops to on

db/migrate/20170617151458_unique_email.rb, db/schema.rb
Modify the schema so that the *database* enforces uniqueness
of email addresses when the provider is 'local'.
We depend on this, because we use the email address as the
identifier during login.
We enforce this at the Rails level, but that is subject to a race
condition because different Rails processes or threads might not
see this.  Also, enforcing important data structure requirements
at the DBMS level means that even if the code has a bug, it can't
violate this condition.
=> Enforce in DBMS that local emails are unique. Fixes #719

app/controllers/users_controller.rb, app/views/users/index.json.jbuilder, app/views/users/show.json.jbuilder, test/integration/users_index_test.rb
We take privacy seriously, so in the past we have only allowed admins
to get the user index.  However, in retrospect this was really
more security theater than real security.  The index information
is available publicly anyway through various means.
The user information (id and name) is easily determined via show
one-by-one.  Whether or not a user is on GitHub, and their nickname,
can be inferred by the external page reference.  And the GitHub uid
is easily determined from GitHub using the nickname and GitHub APIs.
So in short, we're overprotecting information already publicly available.
This is a problem, because we *want* to encourage people to analyze
our data about OSS, and the user list is a key part of that data.
We're just making it hard for legitimate uses.
So, this lets download …
=> Allow download of user index by non-admins

doc/implementation.md
Other researchers will want to download the project data
for further analysis.  Yannick Moy, in particular,
wanted to analyze the data further.  We want to encourage
research - the more analysis that can occur, the more everyone
can understand FLOSS better.
We already support download, but it wasn't as clearly documented.
This commit documents exactly how to download the key project data.
Of course, we do *not* provide some data
(like user email addresses and hashed user passwords),
and this is intentional - so we document that too.
=> Document how to download data for analyis.  Fixes #822

app/views/static_pages/criteria.html.erb, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.ja.yml, config/rails_best_practices.yml
This uses a table, which should be much easier to localize.
Previously we had used running text, which is especially problematic
for languages like Russian that have different endings for different
cardinal numbers (not just singular/plural).
=> In /criteria show information about all levels

db/migrate/20170617213336_index_higher_levels.rb, db/schema.rb
This indexing is key for efficiently querying higher levels
(e.g., for recording the number of silver/gold projects).
=> Index percentages for higher-level badges

app/models/project.rb, lib/tasks/default.rake, test/integration/recalc_test.rb, test/models/project_test.rb
With the addition of the new levels, we will need to update
the higher level badge percentages for all the projects without
affecting the passing level status or modifying the updated at
entry.  These changes allow that and a rake task is added to perform
the action.  The command:
~~~~sh
rake update_all_badge_percentages
~~~~
still updates all levels while:
~~~~sh
rake update_all_higher_level_badge_percentages
~~~~
updates all but the passing level.
This PR provides numerous tests to make sure the methods being
called perform as expected.
=> Modify update_all_badge_percentages to update specified levels

app/models/project_stat.rb, db/migrate/20170617215652_record_higher_levels.rb, db/schema.rb
This partly addresses #813 by recording data in table project_stats.
This commit does not *display* any of this data - but we
have to record it before we display it.
It's not clear we'll report the 25%, 50%, 75%, or 90% levels for
silver or gold, but it's easier to simply start recording it & then
we can show subsets if desired.
=> Record statistics for higher-level badges.

app/views/projects/_status_chooser.html.erb
Partial view status_chooser is the largest consumer of time and memory
as reported by the "Scout" performance monitor.  This makes sense because
it is repeatedly called many times in a loop in project#show and
project#edit.
A minor but easy optimization is to delay calculation of value
criterion_result, so that we only calculate it when we need it
(we don't need it if we're retrieving a cached value).
This doesn't help that much, but it does no harm and from a logical
viewpoint it makes sense to calculate it around the first location of use.
=> Minor optimization: get criterion_result in status_chooser

app/models/criteria.rb, app/views/projects/_status_chooser.html.erb
The criterion description text is from a trusted source, so don't
sanitize every description on every use at run-time.
(We could check once on start-up, if a check is desired; that way,
we would only have to pay for the check once on start-up.)
=> Don't sanitize criterion description

app/views/projects/_status_chooser.html.erb
Cache the generated markdown for project justifications.
Note that these can be *reused* across locales, and when they are
identical these can even be reused across projects
(this can happen when people accept the system-created justifications).
The markdown is generated as part of file
app/views/projects/_status_chooser.html.erb, which is the biggest
user of time and memory allocations, so optimizing this file
is sensible in general.
We use the justification text as the cache key.
This can result in rediculously-long cache keys, but those are exactly
the cases where the cache would be most useful, so we permit it.
=> Cache justification markdown

README.md
We already had a summary of the "passing" criteria in the README.
Here we add summaries for silver & gold.  These summaries aren't the
complete list; they simply give users a quick idea of what the
criteria are like.
=> Add summary of silver & gold to README. Fixes #842

app/views/projects/_status_chooser.html.erb
The status_chooser is a performance hotpoint in this application.
Split the caches into multiple caches, so its results are more
likely to be shared, and completely eliminate the use of
the justification text as a cache key
(this text can be long, make it less than ideal as a cache key).
=> Split up caches in status_chooser

app/models/criteria.rb, app/views/projects/_details.html.erb
This commit accepts the "details" text as html_safe, instead of
doing a more-expensive sanitize on every single detail text
every time it's requested at run-time.  The source of the details
text is trusted, so the "sanitize" is not necessary.
=> Trust "details" source (don't bother sanitizing)

test/models/translations_test.rb
This commit adds a test to ensure that all text values,
in all locales, include only acceptable HTML.  We determine this by
sanitizing (which only accepts a whitelist of tags and attributes),
and then seeing if that's the same as simply regularizing the text
(without removing anything).
If we pass the test, then we can omit sanitization or escaping of
the locale text at run-time with confidence, since we know
that it can only include the permitted tags and attributes.
We also know that *all* the text has been checked ahead-of-time.
That's better for performance (at run-time we definitely don't
need any of those checks) and for error detection (we detect
an unexpected tag or attribute much earlier, and more thoroughly).
Strictly speaking the locale text is trusted anyway, but
adding a test …
=> Test: All text values (all locales) incl. only acceptable HTML

config/brakeman.ignore
Ignore a brakeman report about "projects/_details".
The _details data is from a trusted source, and we check its data values
at test time to counter attack.  Brakeman, of course, does not have
this information, so it reports on a suspicious sequence of events.
=> Ignore brakeman report about _details

app/views/static_pages/criteria.html.erb, config/locales/en.yml
Show the number of brand-new criteria at each level
in the display of "/criteria".
=> Add "new at this level" criteria stats to /criteria

app/views/projects/_status_chooser.html.erb
The "buttons" cache in _status_chooser was no longer  storing
any information on the criterion_result (which is influenced by
the justification text).  This was causing the result_symbol
for various projects to display incorrectly.
This is hard to set up a regression test for, so I have not
made one.  We could perhaps make a long feature test where
we change a criterion's justification text, save and compare
with expected results.
=> Fix caching in status_chooser; fixes #885

config/locales/en.yml
Fix minor grammar text issue in a silver criteria.
Our thanks to @KitsuneRal for reporting this!
=> Fix grammar of silver dynamic_analysis_unsafe. Fixes #875

config/initializers/i18n.rb
We need to pick one sort order for locales. I could see the argument for English-first, but there's no reason why Chinese should go after French. This sorts alphabetically in English (so Chinese comes before English).
=> Sort locales alphabetically for English

config/initializers/i18n.rb
As discussed, keeping the primary language of the site, English, first makes sense.
=> Show English first

config/initializers/monkey_patches.rb
As discussed, concerns are a good substitute for monkey patches and we can add this back in the future if we need it.
=> Delete monkey patch initializer

app/controllers/projects_controller.rb, app/helpers/sessions_helper.rb, app/models/project.rb, app/views/projects/_form_0.html.erb, config/locales/en.yml, test/controllers/projects_controller_test.rb
This adds a user interface so that users can allow *additional*
other users to edit project entries, beyond those already allowed
(owner, BadgeApp admins, and those who can edit that GitHub repo where
that applies).
We expect that in nearly all projects this functionality
will not be used, but that when it's needed it's important.
We've contemplated this functionality for a while,
but most projects haven't asked for it.  However, the PostgreSQL project
informed us that this functionality was important to them, and that
created a clear situation where there *was* a need.
Since this is a rare but important need, this commit implements
a minimal UI that "gets the job done".
The authorization rules implemented here are straightforward:
* If you control a project (are the owner or a BadgeApp …
=> Add user interface for editing project additional rights. Fixes #93

doc/implementation.md
YAML allows comments, but the YAML reformatter removes them.
Move comments to implementation.md, where they will be safer.
=> Move comments from en.yml to implementation.md

lib/tasks/default.rake
My mistake on #899 was caused by running `rake translation:sync` when I thought I was on the master branch but was not. This will avoid a repeat of the error.
=> Ensure master branch

app/views/project_stats/index.html.erb
Some of the new project_stats are probably less useful right now,
so only bother showing them to admins.   This makes loading
project_stats faster for typical users and guests.
The data is made available to the public via JSON,
so no data is lost & anyone can recreate these graphics if they want to.
=> Omit less-useful statistics for non-admins

app/views/projects/_form_0.html.erb
Check that only valid characters are included in
a SPDX license expression on the client.
This isn't a rigorous check, but it eliminates some nonsense.
This commit only checks on the client side (using HTML5 patterns);
we don't need to do more, because invalid SPDX license expressions
aren't a security vulnerability.  Instead, we simply want to
make it a little harder to enter data that is clearly nonsense.
=> Add pickier checks on SPDX license expression on client, fixes #916

app/views/layouts/mailer.html.erb, app/views/report_mailer/email_new_project_owner.html.erb, app/views/report_mailer/email_reminder_owner.html.erb, app/views/report_mailer/email_reminder_owner.text.erb, app/views/report_mailer/project_status_change.html.erb, config/locales/en.yml
Reminder emails were originally being only sent in English.
Add the reminder text to config/locales, and send the *translated* text.
=> Translate reminder emails (fixes #932)

app/helpers/sessions_helper.rb, test/helpers/sessions_helper_test.rb
The "remember me" functionality wasn't working
(when enabled this adds a *persistent* cookie, so that
closing the browser leaves you logged in).
This fixes the bug and the test to match.
=> Fix "remember me" local user functionality, fixes #937

CONTRIBUTING.md
Let's do more two-person review - and say so in the CONTRIBUTING.md file.
=> Proposed change to CONTRIBUTING.md: Two-person review

doc/governance.md
=> We don't accept SMS as 2FA in the BadgeApp for direct contributors

criteria/criteria.yml
The "gold" criteria require justification for practically everything,
instead of requiring URLs for justification.  Since "gold" is a high
standard, it's reasonable to ask for more information (URLs) in
the justification.  One of the main reasons to ask for URLs is to
make it easier for others to verify claims made; it also makes it
easier to look at those badge holders as examples of "how to do it".
Ignoring the criterion "must meet previous level", this means that when
you examine the percentage of criteria that require URLs in justifications,
gold requires a higher percentage (41%=9/(23-1)) compared to silver
(31%=17/(55-1)).
=> Require URLs for a few more "gold" criteria. Fixes #926.

app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/views/users/show.html.erb, config/locales/en.yml, doc/security.md, test/controllers/users_controller_test.rb
On the user page show the user's "additional rights".
These determine the specific rights of
a user, but up to now have not been shown on the user page.
Show them, so that it's completely obvious what rights the user does
(and does not) have.
If you're a logged-in admin, also show on the user's page
if that user is an admin.  It's probably not hard to figure out
who at least some of the administrators are, but this is data
about *people* instead of system *design*.
Add tests, including a number of negative tests
to verify that this data is *only* shown to admins, and document
these negative tests in security.md (we expressly note that we do
negative tests, and this is another good example of this).
=> Show additional rights and admin privilege in user page. Fixes #915

app/views/static_pages/home.html.erb, config/locales/en.yml
This commit modified the front page to add links (as buttons)
to easily share on various social media sites.
I have resisted adding social share links because of
potential privacy concerns, in addition to performance problems.
Sadly, traditional "like" buttons and similar are fundamentally
tracking devices.  We want to respect the privacy of our users, and
certainly do not want to scare off people from using our site.
However, the page "Responsible Social Share Links" provides a solution:
https://jonsuh.com/blog/social-share-links/#use-share-urls
That page describes how to add share links *without* privacy
concerns. If you don't press the link (button), nothing is tracked.
Now people can share when they *want* to do so, without being tracked
by other services when they don't choose to …
=> Add links on home page to easily share on social media. Fixes #927

app/views/sessions/new.html.erb, app/views/static_pages/cookies.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/static_pages_controller_test.rb
The EU and UK have "cookie laws".
More information about the EU cookie laws, from a formal EU site, are here:
* [(EU) Information Providers Guide - Cookies](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)
* [ePrivacy directive, especially Article 5(3)](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:32002L0058:EN:HTML)
It's not clear that these laws applies to the site:  I'm a US citizen,
this site is run in the US, and the primary organization running the
site (the Linux Foundation) is a US organization.  In addition,
[NoCookieLaw](http://nocookielaw.com/) has a valid point: these laws seem
to be completely pointless, since they doesn't actually provide any *real*
privacy (and ignore the *real* and serious privacy problems).
However, in our case, it looks like all …
=> Add info about cookies to comply with EU and UK "cookie laws". Fixes #938

app/views/static_pages/home.html.erb
It's conventional to have share links at the top or bottom of
the page, so they're easier to find - force them to be at the bottom.
=> Force "share" links to bottom of home page, regardless of width

app/assets/stylesheets/static_pages.scss, app/views/projects/_status_chooser.html.erb
When there's enough width, move the criteria text to the right of
the chooser.  The justification text continues to be below the
chooser, to maximize the amount of space available for long answers.
We originally moved the criteria text to a new line because the Russian text
was too long in the original format.  That solved one problem,
but created a new one.
As @KitsuneRal noted, "I have to say though that criteria take a lot
of vertical screen estate now that the radio group is displayed in
a separate div from the text and both are float: left. And since the
current representation doesn't map to the conventional "question-response"
arrangement, I already caught myself once mistakenly associating the radio
group with a criteria above, not below - though the (barely visible on
poorer …
=> Move criteria to right of status chooser when there's room (fixes #862)

app/helpers/sessions_helper.rb, app/views/projects/edit.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, config/locales/en.yml, test/features/login_test.rb, test/integration/project_get_test.rb, test/integration/users_manipulate_project_test.rb
This displays an alert to users if they are not on the production
site.  This helps prevent users from entering information on the
wrong website which could be lost.
=> Warn users if they are on a development site; Fixes #962

app/controllers/projects_controller.rb, app/mailers/report_mailer.rb, app/views/projects/delete_form.html.erb, app/views/projects/show.html.erb, app/views/report_mailer/report_project_deleted.text.erb, config/locales/en.yml, config/routes.rb, test/controllers/projects_controller_test.rb
Currently people sometimes delete project badge entries and
we have no idea why.  Also, although we required confirmation
before deletion, it was still very easy for people to
accidentally delete project entries.
This commit changes the "delete" UI link to instead present
a special form (delete_form),
where we "require" a deletion rationale.
That deletion rationale is included in the email to admins
that occurs when a project is deleted.  This makes it
much less likely that a deletion will happen by accident,
and the rationale may help us better understand why some
people delete project entries.
We only use HTML to "require" the deletion rationale, and don't
bother to check that on the server, since failing to provide
this information isn't a security issue.  We just would like to know. …
=> Require rationale to delete project and report it

app/controllers/projects_controller.rb, app/views/projects/_project.json.jbuilder, app/views/projects/badge.json.jbuilder, test/controllers/projects_controller_test.rb
We already supported /projects/:id/badge and by default that is SVG.
Add support for /projects/:id/badge.json so that external queries
can easily determine the badge level of a project.  The reply
includes "badge_level" which is one of the short badge level names
("in_progress", "passing", "silver", or "gold").
For consistency, also provide badge_level when replying with a full
JSON response for a project (e.g., /projects/:id.json).
=> Add support for /projects/:id/badge.json and include badge_level in JSON

app/assets/javascripts/project-form.js, app/lib/floss_license_detective.rb, app/lib/hardened_sites_detective.rb, app/lib/project_sites_https_detective.rb, app/lib/repo_files_examine_detective.rb, app/lib/subdir_file_contents_detective.rb, app/models/project.rb, config/locales/en.yml, db/migrate/20180124232626_revise_comment_marker.rb, db/schema.rb, test/models/project_test.rb, test/unit/lib/subdir_file_contents_detective_test.rb
Up to now, if a justification textbox begins with "#", optionally
preceded by spaces, it is considered a "justification comment"
(and is not considered a justification for purposes of an Unmet SHOULD
or where a justification is otherwise required). That made sense because
in many programming languages, "#" introduces a comment that ends at
the end of the line.
In retrospect, that was a mistake, because "#" also has a meaning in
markdown - the beginning of a header. This means that justification
comments look really wonky when viewed (though they look fine while
they're being edited).
We need to change things somehow. The simplest approach, taken here,
is to switch to leading "//" (possibly preceded by spaces) as the
marker for a justification comment. This is a comment marker in many …
=> Change justification comment mark from '#' to '//' fixes #1009

circle.yml
Install *current* version of bundler early in CircleCI.
=> In CircleCI run "gem install bundler"

app/controllers/users_controller.rb, app/views/projects/_table.html.erb, app/views/projects/show.html.erb, app/views/users/show.html.erb, app/views/users/show.json.jbuilder, config/locales/en.yml, test/controllers/users_controller_test.rb
Change how we handle users so that users can delete their own accounts
and show their own email addresses.  The purpose of these changes is
(in part) to comply with the EU General Data Protection Regulation (GDPR)
as we understand it.
This commit enables users to delete their own user accounts to support the
EU 'right of erasure'.  The application requires that every project
entry have an 'owner', so we only allow user account deletion if
a user owns no project entries.  Since users can always delete project
entries if they own them, users can always delete their accounts without
any action from an administrator.
This commit also enables users to show their own email address (in both
the HTML and JSON format).  This supports the GDPR "right of access"
where users must be able to see the …
=> Enable users to delete their account and show email (GDPR)

Procfile
Disable exec-load in Procfile to eliminate a false puma error
at runtime on Heroku.  This is a tiny but non-obvious change, so this
commit message provides lots of detail.
Every day we typically get incorrect error reports of the following form:
> heroku/web.1: Process exited with status 1
This is caused because Heroku cycles the webserver (puma) by sending
SIGTERM, but when puma exits it incorrectly returns an error code of 1
("error occurred"). That is simply wrong; a process that exits because
it was specifically asked to do so (via SIGTERM) has not experienced an
error. Instead, exiting on a request to do so, without any other error,
is correct behavior and should return a status code of 0. However,
because puma incorrectly reports a non-zero error code, lots of other
logs whine about …
=> Disable exec-load to eliminate false puma error; fixes #1026

app/controllers/projects_controller.rb, app/views/projects/delete_form.html.erb, config/locales/en.yml, test/controllers/projects_controller_test.rb
Perform a server-side check of the deletion_rationale for projects,
making the check non-bypassable.  This isn't necessary for security,
but it ensures we get *some* text from the user. Hopefully the text is
useful, and in any case this provides a stronger defense against
accidental deletion.  This commit also adds some tests to ensure it works.
The proposed rule is "at least 20 characters and at least 15
non-whitespace characters".  That will at least prevent someone
accidentally providing a bunch of returns.  If people really insist
on giving us garbage (e.g., a bunch of "a"s) we don't
want them involved anyway.
The check isn't require for admins, who presumably know what they're
doing (and can fix it if they make an error).  That way, if an admin
has to delete a bunch of garbage …
=> Add server-side check of project deletion_rationale, fixes #1022

app/views/report_mailer/project_status_change.html.erb, app/views/report_mailer/project_status_change.text.erb, config/rails_best_practices.yml
In the emailed report to admins, report the project entry
created_at time and (where appropriate) the difference
between the created_at time and the achieved_passing_at time.
This will help highlight "unusually speedy" badge achievements,
e.g., so that we can review those more closely.
=> Include times in admin notification, fixes #1035

app/views/static_pages/robots.text.erb, config/initializers/i18n.rb, doc/implementation.md, test/features/robots_contents_test.rb
This modifies the BadgeApp's "robots.txt" to disallow crawling
(and thus indexing) of anything in /users, including /LOCALE/users.
The GDPR is obviously very sensitive about user data, and we display
some user data. If another site crawls/scrapes/spiders the data (say for a
web search), then I think it's primarily the problem of the other site to
ensure that the data disappears in a reasonable period of time.
That said, we can make it much less likely that user data will show up
in spidered data at all, by expressly telling spiders to not look at
those pages. Then, if a user account is deleted, that user data will
disappear much more quickly. In addition, if we make a mistake and
accidentally provide private data (primarily the email address), it won't
be indexed in other places in most …
=> Modify robots.txt to disallow /users (fixes #1027)

app/controllers/projects_controller.rb, test/controllers/projects_controller_test.rb
Remove trailing "/" in URLs when trying to create a project entry.
Most URLs that people submit do not have trailing "/", but
a non-trivial number do have a trailing "/", and this makes it
a little harder to notice duplicates.  Remove the trailing "/"
on initial create.
This doesn't prevent later changes, especially of the homepage_url,
but it reduces the number of initial problems.
=> On project create, rm trailing / in URLs

app/controllers/projects_controller.rb
Force cleanup of homepage_url (removing trailing "/")
so unintentional duplicates are easier to find.
=> Clean up homepage_url during update

Procfile, ignore-termerr
This should stop Heroku from falsely reporting a problem
that is merely caused by correct termination and restart.
=> Modify Heroku startup to stop reporting on SIGTERM

app/views/layouts/application.html.erb
Speed up first-time display by hinting to the web brower
to download the font awesome fonts.  The browser will eventually
figure that out, but only after it parses the CSS and more of the HTML.
Include the hint in the HTML head, so that the browser can
initiate the request sooner.
This doesn't matter after the first-time display, because the
fonts will almost certainly be cached, but this is an easy
optimization for first-time display.
=> Preload font awesome fonts

app/views/layouts/application.html.erb
The application.html.erb page is used to generate every HTML page.
Cache most of its header to improve average response time.
Note that we intentionally do *not* cache csrf_meta_tags.
=> Add cache to app/views/layouts/application.html.erb

app/helpers/application_helper.rb, app/views/layouts/_header.html.erb, app/views/projects/index.html.erb, app/views/projects/show.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, config/locales/en.yml, doc/implementation.md
This commit adds icons to all major navigation-level actions,
and switches the ones that existed to all use font awesome.
This improves the look, and is a step towards eliminating
glyphicons and subsetting font awesome (to speed first-time display).
It also tweaks the login and signup text to make it clearer that
logging in via GitHub does an automatic sign-up.
One challenge is that in English "sign in" and "sign up"
are different operations, but they sound similar and are related,
so it's easy for people to be confused.
In addition, because we want users to have *convenient* experience,
users who sign in using GitHub also have an automatic sign up
(if necessary).  We tried to be clear before - hopefully these
changes will make it even clearer.
Signed-off-by: David A. Wheeler …
=> Use more font awesome and tweak signup text

app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
Make a few small improvements for performance:
Add a locale-sensitive cache for the footer, and use "-%>"
in various places so that newslines aren't being included
(in some cases this eliminates a separate newline concatenation;
every separate concatenation request hurts performance).
=> Mildly optimize views/layouts

app/helpers/projects_helper.rb
Add nofollow to discourage search engines from following
all the pages that are just different sort orders.
=> Add "nofollow" for headings

app/controllers/sessions_controller.rb, app/helpers/sessions_helper.rb, config/locales/en.yml, db/migrate/20180218221750_add_login_at_to_user.rb, db/schema.rb
Record the last_login_time in user record when a user logs in.
This makes it easier to see what users are active, and can
help users detect if someone else has been abusing their account.
This will also make it easier to record how many different
users have been logged in over some period of time.
=> Record last_login_at time in user record

app/helpers/project_stats_helper.rb, app/views/project_stats/index.html.erb, config/locales/en.yml, test/controllers/project_stats_controller_test.rb
Clean up code to simplify slightly.
This also adds some tests, as the process of cleaning up the
code revealed that the tests needed to be improved.
This commit adds a test for the "as admin" case of seeing
project stats, and adds simple checks of the contents of the response.
=> Minor code cleanup of /project_stats chart code

app/helpers/application_helper.rb, app/models/icon.rb, app/views/layouts/_header.html.erb, app/views/projects/index.html.erb, app/views/projects/show.html.erb, app/views/users/show.html.erb, config/initializers/icon.rb, test/models/icon_test.rb
This creates an "Icon" class to precompute and provide
HTML for icons.  Icons are used in all HTML output, so
it makes sense to precompute it for performance.
=> Precompute HTML for icons

app/helpers/sessions_helper.rb, app/views/layouts/application.html.erb, config/initializers/canonical_trailing_slash.rb, config/routes.rb, doc/implementation.md, test/controllers/projects_controller_test.rb, test/controllers/static_pages_controller_test.rb, test/helpers/sessions_helper_test.rb
This adds link rel="alternate" metadata to make it much
easier to find the alternate locales for various pages.
It includes an "x-default" locale, which eases
automatically finding the "no locale" URL.
It also adds link rel="publisher" so that it's clear
who the publisher is.
This should help search engines find (and understand) the site.
That's especially important now that the site is automatically
redirecting based on locale.
For more information, see:
https://support.google.com/webmasters/answer/189077?hl=en
https://searchengineland.com/
the-ultimate-guide-to-multilingual-and-multiregional-seo-157838
=> Add link alternate and publisher metadata

app/controllers/projects_controller.rb, app/controllers/users_controller.rb
Redirects within the same domain can use _path or _url.
This commit changes many redirects to use _path instead of _url.
A _path is shorter, is invariant between test and production,
yet browsers will end up at the same place.
=> Change some redirects to use _path, not _url

app/mailers/report_mailer.rb
Fix the URL in some emails ("." should be "/").
The problem is that we used the wrong helper; we used
"projects_url" (plural name) when we should have used
"project_url" (singular name).  We're referring to a
singular project, so we must use the singular helper.
=> Fix URL in email ("." should be "/").  Fixes #1096

app/models/user.rb, test/features/login_test.rb
We previously checked email uniqueness in the user model, and
unintentionally required that the email be globally unique.
This commit instead requires case-insensitive uniqueness *only*
for local accounts, completely ignoring GitHub users (who are
handled differently).  In particular, we had a user who had
both her local account and GitHub account tied to the same
user email address; that should have worked, but didn't because
of the overly-restrictive check.
Note that this commit includes a regression test, one that did
*not* pass before but passes now.
=> Require user email uniqueness ONLY on local accounts

app/views/static_pages/error_404.html, app/views/static_pages/error_404.html.erb, config/locales/en.yml
Internationalize (i18n) the "not found" (404) page.
This is intentionally short and does *NOT* use the standard layout,
to minimize CPU and bandwidth use during an attack.
It's cached per locale, speeding later replies for a given locale.
=> Internationalize (i18n) the "not found" (404) page. Fixes #1111

config/locales/en.yml
Add more text to clarify exactly what we do with user names
(both full name and nicknames) and email addresses.
It's not clear that we need to add this text
to comply with the EU GDPR, but more clarity is a good idea
whether or not it's strictly required.
=> Clarify exactly what we do with names and email before signup

config/initializers/callback_terminator.rb
Rails 5 changed how callback chains are interpreted. See:
https://blog.bigbinary.com/2016/02/13/
rails-5-does-not-halt-callback-chain-when-false-is-returned.html
This commit restores the old semantics, until we're confident that
things work correctly with the new semantics.  If we need to, we can
change some things, but the point of this commit is to simply ensure
that we're using the *expected* semantics.  We will then walk through
all the actions to make sure that there are no problems.
This commit causes the following *expected* deprecation warning:
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false=
is deprecated and will be removed in Rails 5.2. (called from ...)
Once everything has been reviewed, we'll remove the setting
(which will eliminate the deprecation …
=> Tell system to stop callbacks when they return false

config/locales/en.yml
We've received some emails that suggest that people are trying
to change the reminder status, but don't realize that they're
only in *show* mode and not *edit* mode.  Show and edit look
similar, but checkboxes in particular look nearly identical,
and that appears to be leading to the problem.
This commit addresses the problem by changing the text to try
to make it ABUNDANTLY clear that you have to EDIT the project
entry to change this value (just like any other value).
In the long term, we want to make it possible to link
*directly* to the edit mode for this value, to simplify this
further.  However, that requires non-trivial code changes,
and we would STILL want it to be clear to users anyway.
So let's make the situation clear with text right now,
because we *CAN* do that right now, …
=> Clarify: must EDIT project entries to change reminder status

app/views/project_stats/index.html.erb, config/locales/en.yml, test/controllers/project_stats_controller_test.rb
This reduces delay and memory use, and fixes a bug.
Currently, when the project_stats page is shown, it's
supposed to show more graphs to admins.  This leads to a
rediculous amount of delay and memory use when the admin displays
the project_stats page, as well as some errors in display.
This commit instead shows the simple project_stats page in the
normal case, and shows *only* the less-common graphs if you include
"?type=uncommon" ("show the uncommon graphs").  This means that
you only see a particular set of graphs for any particular request.
=> Modify project_stats page to use ?type=uncommon

app/controllers/application_controller.rb, app/controllers/password_resets_controller.rb, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/helpers/sessions_helper.rb, config/initializers/callback_terminator.rb
Rails 5 changed how callback chains are interpreted. See:
https://blog.bigbinary.com/2016/02/13/
rails-5-does-not-halt-callback-chain-when-false-is-returned.html
In short, returning false DOES NOT stop the chain any more.
Rendering or redirecting still halts the chain (in development, this
produces a "Filter chain halted as .... rendered or redirected" message).
If you want to halt the chain, but do not render or redirect,
you can use this to halt the chain: throw(:abort)
This changes the code to throw an exception instead of just returning false,
and also renames several chain entries to make it clear that they
do NOT simply return a true/false value.
Thankfully, in almost all cases we were already invoking
render or redirect_to when we wanted to stop the chain.
Our negative testing also …
=> Eliminate ActiveSupport.halt_callback_chains_on_return_false = true

app/views/static_pages/home.html.erb
The link in the graphic "some badge earners" for Prometheus links to https://bestpractices.coreinfrastructure.org/en/projects/i486 instead of https://bestpractices.coreinfrastructure.org/en/projects/486 (i486 instead of 486).
=> Link to Prometheus on startpage is wrong

app/views/users/show.html.erb, config/locales/en.yml
The GDPR requires some sort of "portable format" for user data.
We have elected to provide this data in JSON format.
We've provided this data for some time, but the web page
didn't have a link to the JSON format.  It was *documented* how
to get this data in the API, but that's not the same thing.
This commit adds a hypertext link that makes it easy to see the
user data in JSON format.  Those who are not logged in, or are
logged in as a different non-logged-in user, will only receive the
*public* user data in JSON format.  This is just information such
as the public name, creation datetime, and last change datetime.
Logged-in users who look at their own data, and admins, will also see
in the JSON format the private data (which is currently the user email
address and preferred locale). …
=> Add hypertext link for seeing user data in JSON format

.env, Gemfile, Gemfile.lock, app/mailers/user_mailer.rb, app/models/project.rb, app/models/user.rb, app/views/projects/reminders_summary.html.erb, app/views/users/show.html.erb, config/initializers/filter_parameter_logging.rb, db/migrate/20180525145445_add_encrypted_email_to_users.rb, db/schema.rb, doc/implementation.md, doc/security.md, test/fixtures/users.yml
This commit encrypts email using two gems,
attr_encrypted and blind_index, that are designed
specifically for this purpose.
At this point many tests don't pass for unknown reasons.
=> Encrypt email using attr_encrypted and blind_index gems

lib/tasks/default.rake
Use "update_column" so that updated_at isn't changed, and also
to do things more quickly.  There are no model validations that
can be affected setting this boolean value, so we can skip them.
=> Change rake fix_use_gravatar to use update_column

lib/tasks/default.rake
Run fix_use_gravatar 1/month, so that if users remove or add
a gravatar, but don't tell us, we'll eventually figure it out.
Heroku scheduler's built-in capability only lets us
schedule things hourly or daily, so we can't set it up directly
in the Heroku scheduler.  But that's not a problem, because
we already have a mechanism built on that to run monthly...
so let's just use that.
=> Run fix_use_gravatar 1/month

app/controllers/sessions_controller.rb
Enable git login when the email keys aren't available.
This makes it easier to test the system without making
the email keys available. That's a good thing, because
the more activities that don't require the keys, the
easier it is to protect those keys.
I had previously done this by rescuing the exception
raised if OpenSSL can't decrypt things, and then I had
to test that case, etc.
This commit instead does something much simpler:
instead of save!, just use update_columns.
Then there's no need to decrypt anything, so there's no error
to be triggered in the first place.  It also means that
we don't change the updated_at value of users merely when
they log in, which seems like a more appropriate use of
updated_at.  Now update_at is still changed when user-visible
data changes (such as the …
=> Enable git login when the email keys aren't available (simpler way)

app/models/user.rb, app/views/users/show.html.erb, app/views/users/show.json.jbuilder, test/models/user_test.rb
GDPR's "data portability" requirements require that we
provide users our data about them in a portable way.
We provide data in JSON format.  This commit adds a few
much-less useful fields, with the goal of providing
everything we reasonably can.  We don't want to share
digests, since in some circumstances those are like passwords
and they are randomly generated anyway.
That said, we can provide these, so let's do so:
*  json.activated
*  json.activated_at
*  json.reset_sent_at
*  json.last_login_at
*  json.use_gravatar
=> Add more fields to exported JSON user data

app/models/user.rb, lib/tasks/default.rake, test/models/user_test.rb
A critical property of keys and passwords, from a security viewpoint,
that it is *easy* to change them if they are revealed.
That doesn't work if there's no easy way to change them.
Here we provide a mechanism to rekey email addresses, if needed.
Most of the functionality is in the User model, so it's
a little easier to test.
=> Add a task to allow rekeying of email addresses

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/sessions_helper.rb, app/views/sessions/new.html.erb, app/views/users/new.html.erb, config/initializers/deny_login.rb, config/locales/en.yml, doc/implementation.md, test/controllers/sessions_controller_test.rb, test/controllers/users_controller_test.rb, test/helpers/sessions_helper_test.rb
Implement the BADGEAPP_DENY_LOGIN mode.
If a non-blank value is set ("true" is recommended)
on the environmental variable BADGEAPP_DENY_LOGIN,
then no on can log in, no one can create a new account (sign up),
and no one can do anything that requires being logged (users are always
treated as if they are not logged in).
This essentially prevents ANY changes by users (daily statistics
creates are unaffected).
From a security POV this is enforced by SessionsController#create (login),
UsersController#create (create new user/sign up), and
SessionsHelper#current_user (determine who current logged-in user is).
Some views disable the login and sign-in display, so that it's more
obvious to user what is going on.
This may be a useful mode to enable if there is a serious exploitable
security …
=> Implement BADGEAPP_DENY_LOGIN mode

app/lib/client_ip.rb, config/initializers/rack_attack.rb, test/unit/lib/client_ip_test.rb
This commit uses results from testing to configure the
Rack::Attack gem so that it gets accurate client IP addresses.
=> Fix rack-attack configuration for our production environment

app/controllers/static_pages_controller.rb, config/routes.rb, test/controllers/static_pages_controller_test.rb
If there's no such page, and no locale in the URL,
we've been redirecting to a URL with a locale.
This wastes time in a round-trip and two calls for
no such page.  Instead, simply reply with an error page.
This results in less code and is faster.  It also eliminates
an bug where we redirect to "/" if given a URL
that looks like a locale ("/no-such-page").
This commit includes a number of extra tests to test various
circumstances. In particular, in error pages
we use the URL locale if given, and if there isn't one, we use
'Accept-Language' header provided by the browser to
determine the locale to use in an error page.
This also stops trying to figure out the locale for
/robots.txt.  We don't need that information at all, robots.txt
doesn't depend on the locale.
Signed-off-by: David A. …
=> Do not redirect if there is no such page and no locale

app/views/projects/_form_0.html.erb, app/views/projects/_form_1.html.erb, app/views/projects/_form_2.html.erb
The submit form accidentally had the word "edit" after the
project number because of how the form helper was used.
It doesn't *matter* because the extra text is ignored,
but it looks odd, and we want to keep everything clean.
=> Make submit URLs /projects/NUMBER not /projects/NUMBERedit

app/helpers/projects_helper.rb, test/helpers/projects_helper_test.rb
To discourage SEO spam we generate rel="nofollow" in the hypertext link
for project_homepage_url and project_repo_url. We should do that for all
user-provided data.  This commit eliminates a missing case, namely,
do this with markdown data from users in the project badge entry page.
=> Add rel=nofollow to generated markdown hyperlinks, fixes #1185

app/helpers/projects_helper.rb, app/views/projects/_table.html.erb, config/locales/en.yml, test/helpers/projects_helper_test.rb
Add a tooltip on the /projects table for each tiered percentage value,
to explain it in detail.  This should make it easier for
newcomers to understand what numbers like "187%" means.
=> Add tooltip on /projects table to explain tiered percentage, fixes #1175

app/lib/floss_license_detective.rb, app/views/projects/_form_0.html.erb
Update to the SDPX 3.0 license list in the dropdown suggestions. See:
* https://spdx.org/news/news/2018/01/license-list-30-released
* https://spdx.org/licenses/
The key difference is that GPL-related licenses, like GPL version 2.0,
are now "GPL-2.0-only" or "GPL-2.0-or-later".  See the announcement
for more information.
=> Update recommended license list to SPDX 3.0. Fixes #1192

config/environments/production.rb
In production, set config.assets.compile = false
as a minor speed and memory performance improvement.
This is recommended by Heroku's documentation at:
https://devcenter.heroku.com/articles/rails-asset-pipeline#
compile-set-to-true-in-production
which says: "If you have enabled your application to config.assets.compile =
true in production, your application might be very slow...
This setting is also known to cause other run-time instabilities and is
generally not recommended. Instead we recommend either precompiling all
of your assets on deploy (which is the default)..."
=> In production, set config.assets.compile = false

app/controllers/application_controller.rb
Use the new security header, "feature policy", to disable things
we don't need. It's already supported by Chrome and Safari.  See:
https://scotthelme.co.uk/a-new-security-header-feature-policy/
=> Add new HTTP security header 'Feature-Policy'

config/locales/en.yml
Criterion documentation_interface noted some programming languages
for some tools, but many other criteria didn't include that information,
and we didn't list many entries for R.
Expand on this information, so that developers can easily see
some tools for the programming languages their projects use
(either as things to consider or as examples they already know about).
We are *not* trying to create a complete list - we're simply providing
some information to help people.
=> Identify many R tools and identify languages for some other tools

.circleci/config.yml, lib/tasks/default.rake
Ignore CVE-2018-1000544 (a vulnerability in rubyzip).
It does not affect production. See:
https://github.com/coreinfrastructure/best-practices-badge/issues/1222
https://github.com/rubyzip/rubyzip/pull/371
https://nvd.nist.gov/vuln/detail/CVE-2018-1000544
=> Ignore vulnerability CVE-2018-1000544 in rubyzip

app/views/layouts/_header.html.erb, config/locales/en.yml
If the screen width is narrow (e.g., a smartphone), we show a
collapsible navigation bar, but we did not have an accessibility
label for it.  That's a problem for blind users.
This commit adds an aria-label to the navbar-toggle.
Since it's a text label, it must be internationalized.
=> Accessibility fix of collapsible navigation hamburger, fixes #1217

app/controllers/static_pages_controller.rb, app/views/static_pages/google_verifier.txt, config/routes.rb, test/controllers/static_pages_controller_test.rb
We need to receive Google notifications about problems with our site that
are generated by Google's webcrawler. In particular, I need to be able
to see them! To do this, we need to tweak our routes so that this URL:
https://bestpractices.coreinfrastructure.org/google75f94b1182a77eb8.html
Will generate this content exactly:
google-site-verification: google75f94b1182a77eb8.html
=> Enable David A. Wheeler to get log issues from Google, fixes #1223

config/locales/en.yml
Criterion know_secure_design says that
"The project MUST have at least one primary developer
who knows how to design secure software."
However, if you don't have the details showing, it's not obvious
what that really requires; the details provide that information.
That's technically true for many criteria, but for this particular
criterion that is *especially* important.
This commit simply adds a note,
"(See ‘details’ for the exact requirements.)".
There's no substantive change, but we hope that this change
will make it easier to apply.
See the discussion here:
https://github.com/coreinfrastructure/best-practices-badge/issues/1211
=> Clarify know_secure_design depends on details.

app/views/projects/_form_0.html.erb, config/locales/en.yml
Make it clear in the section for entering SPDX license expressions
that single quotes and double quotes should not be included.
Note that in both the details and in the field title
(as a side-effect, internationalize the field title).
We hope that this will resolve this reported problem:
https://github.com/coreinfrastructure/best-practices-badge/issues/1226
That said, even if this doesn't resolve *that* problem, clarifying
what we need and internationalizing the title is a good idea.
=> Clarify that SPDX license expressions do not include quote marks

config/locales/en.yml, test/features/login_test.rb
We have a message saying
"We have updated our requirements for the criterion static_analysis",
but the Rails semantics for safe HTML in flash messages has changed.
As a result, its formatting is now wrong.
Instead of trying to significantly rework
app/controllers/projects_controller.rb, just remove the
not-really-necessary hypertext link.
This message only occurs in rare situations, and the hypertext link
isn't all that important.
=> Fix format of "we have updated our requirements" text

app/views/projects/_form_0.html.erb
If someone edits additional rights, the changes don't
necessarily show on the project list, because we show the
old cached value instead.
This commit adds the list of additional rights to the cache key.
This ensures that when the list changes, the cache is invalidated.
If the performance is too slow, we could directly expire this
specific cache entry instead.  However, that adds a maintenance headache:
that would then create a subtle dependency on the cache key.
So let's try the "hard to get wrong" approach first, and switch
to the faster-performing version only if necessary.
I don't expect it to really impact performance, because for most
project this is an empty list.
=> If additional rights list changes, invalidate cache. Fixes #1255

doc/criteria-footer.markdown, doc/criteria.md
This is a re-implementation of pull request #1244 by @marctjones per
https://github.com/coreinfrastructure/best-practices-badge/pull/1244
This commit adds a newline to separate the footer text from generated text.
This version, unlike the version from @marctjones, has a DCO signature
and modifies the source file doc/criteria-footer.markdown
(doc/criteria.md is a generated file).
My thanks to @marctjones for bringing this to our attention and
creating a first crack at it!
=> Add newline in criteria, fixes #1244

app/views/projects/_project.json.jbuilder, app/views/projects/show_json.json.jbuilder, test/controllers/projects_controller_test.rb, test/vcr_cassettes/unit_test_github_basic_detective.yml
Our JSON output for a project didn't include additional_rights
information because that is not stored in the projects table
(it's in another table).  However, it's clearly relevant to a project.
Therefore, add the additional_rights field to the JSON output.
We'll output it as a JSON array (that seems like the best way to
model it).
=> Add additional_rights to JSON output, fixes #1272

config/initializers/cors.rb, test/controllers/users_controller_test.rb
Allow access to .json data to individual users
by client-side JavaScript by adding it to the
CORS access control list.
This also adds tests to ensure that we force no caching
of user data.  We disable caching to greatly reduce the
risk of an unintentional leak of user data via a cache.
=> Allow CORS access to individual user data

.circleci/config.yml, lib/tasks/default.rake
Ignore CVE-2015-9284 (a vulnerability in omniauth). We have mitigated this with a third-party countermeasure (omniauth-rails_csrf_protection) in #1298
=>  Ignore vulnerability CVE-2015-9284 in omniauth

doc/api.md
Simplify finding information about the `tiered_percentage`
field by specifically discussing it in doc/api.md.
=> Document tiered percentage in doc/api.md

config/locales/en.yml
The word "communications" was incorrectly spelled "comunications"
(one m) in criterion crypto_used_network.  Fix the mispelling.
Our thanks to @TonyLHansen for reporting this!
=> Fix misspelled word "comunications". Fixes #1304

.circleci/config.yml, CONTRIBUTING.md, config/database.ci.yml, dockerfiles/2.5.1-stretch/Dockerfile, dockerfiles/README.md
Our CircleCI configuration was woefully outdated, running on an ubuntu 14.04 image.  This PR updates the CircleCI config to run on a custom ruby:2.5.1-stretch image.
Also included is a Dockerfile to build the custom image and documentation updates.
=> Update CircleCI configuration

lib/tasks/default.rake, test/test_helper.rb
This PR fixes the rake file so that webdriver is
not required in production.
=> Fix webdriver deps

app/views/layouts/application.html.erb, app/views/project_stats/index.html.erb
Chartkick doesn't work well with Turbolinks, because it requires a
"load" event that turbolinks does not provide.
Disable turbolinks in hyperlinks *to* the page that uses Chartkick.
=> Disable turbolinks-cache-control due to incompatibility with Chartkick

app/views/project_stats/index.html.erb
Modify HTML head to make /project_stats work with turbolinks.
Instead of using name="turbolinks-cache-control" content="no-cache",
use name="turbolinks-visit-control" content="reload".
For more information, see:
https://github.com/turbolinks/turbolinks#
ensuring-specific-pages-trigger-a-full-reload
=> Force reload in /project_stats via turbolinks-visit-control

app/helpers/users_helper.rb, doc/requirements.md, doc/security.md
Document that avatar services are considered "related sites"
for purposes of security/privacy, and explain what they're all about.
In addition, add the experimental
`referrerpolicy="no-referrer"` attribute to the avatar image
as discussed in the
[Mozilla img documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)
to provide additional privacy.
We aren't required to do this by our policies, but in general we
try to maximize privacy while still providing our services.
=> Document avatar security/privacy and add a little privacy

app/assets/stylesheets/projects.scss, app/helpers/projects_helper.rb, app/views/projects/_table.html.erb
The "projects" table is wide, and that's a problem for
narrow screens (especially on mobile).
Part of the problem is that URLs don't easily break,
and some project names use characters like underscores
that are not automatically word breaks.
To resolve this, add word break hints on project names and
URLs, and also add word-wrap: break-word on project names
(word-wrap is already set on URLs).
=> Add word breaks and break-word to project table

app/views/layouts/_header.html.erb, app/views/projects/delete_form.html.erb, app/views/projects/edit.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, doc/implementation.md
Add a "system announcement" capability.
If environment variables SYSTEM_ANNOUNCEMENT
(and optionally SYSTEM_ANNOUNCEMENT_locale) are set, show them on
every application page as an announcement.
The immediate purpose is so that we can warn about a
soon-to-occur brief shutdown for a database upgrade.
But this is a general-purpose mechanism that can be used for other
purposes as well.
=> Add a "system announcement" capability

config/initializers/new_framework_defaults.rb, doc/security.md
To improve security, by default Rails 5.2 changed to embed
the expiry information in encrypted or signed cookies value.
This commit switches to the Rails 5.2 default, which hardens our
software. As a side-effect, this logs off all users.
Up to this point we have disabled the Rails 5.2 default because we
didn't want to force a mass logoff by all users.
We disabled it by setting
Rails.application.config.action_dispatch.use_authenticated_cookie_encryption
to false.  However, now that we have a new "announcement" mechanism,
we can *warn* users before they get logged off.
So now we can switch to this new behavior without hurting our users.
For more information, see
[Upgrading Ruby on Rails expiry info](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#expiry-in-signed-or-encrypted …
=> Embed expiry in cookies (FORCES LOGOFF BY ALL USERS)

doc/implementation.md, lib/tasks/default.rake
Add a new rake task named "change_owner" to simplify the process
of changing the owner of a project. Local use is:
~~~~
rake change_owner -- PROJECT OWNER
~~~~
Where PROJECT is the project badge entry number and OWNER is the user id
of the new owner.
You can run this remotely (if authorized) as:
~~~~
heroku run --app production-bestpractices rake change_owner -- PROJECT OWNER
~~~~
We can already do this by running a SQL command, but an error
(such as forgetting a WHERE clause) could lead to a big mistake.
This task also shows related information (including how to revert it),
which reduces the risk of a mistake and simplifies recovery from one.
=> Add rake task change_owner -- PROJECT NEW_OWNER

README.md, doc/vetting.md
Issues
https://github.com/coreinfrastructure/best-practices-badge/issues/1349
and
https://github.com/coreinfrastructure/best-practices-badge/issues/1351
asked questions about vetting. We had documented this in
some presentations, but clearly people were not finding this information.
This commit adds a markdown file specifically about badge vetting
(what we do and why we do it that way).
=> Add more about vetting

app/controllers/projects_controller.rb, config/locales/en.yml, db/migrate/20191021173151_add_repo_url_updated_at_to_projects.rb, db/schema.rb, doc/security.md, test/controllers/projects_controller_test.rb
Allow a project to modify its repo_url, but only after
REPO_URL_CHANGE_DELAY days (currently 180 days) since the last
time its repo_url changed.  This should reduce admin effort
while still countering a subtle attack.
We are trying to counter subtle attacks where
a project tries to claim the good reputation or effort of another project
by constantly switching its repo_url to other projects and/or nonsense.
The underlying problem is that names/identities are hard; the repo_url
(when present) is the closest to an "identity" that we have for a project.
We have to allow it to change sometimes (because it sometimes does), but
it should be a rare "sticky" event.
There are various special cases, e.g., you can always set the repo_url
if it's nil, the setter is an admin, or if only the scheme is …
=> Allow repo_url mod if REPO_URL_CHANGE_DELAY days pass

criteria/criteria.yml
The text of silver criterion implement_secure_design
expressly allows N/A, but the UI does not permit N/A.
Fix that.
This fixes fixes #1354.  We thank @fzipi for reporting this!
=> Allow N/A in implement_secure_design, fixes #1354

config/locales/en.yml
Fix a trivial word error in silver criterion
crypto_credential_agility. In the text
"permit users to update and replacement them ...",
change the word "replacement" should be "replace".
=> Fix typo in crypto_credential_agility; fixes #1340

doc/security.md
Systems that use CDNs can be vulnerable to the
Cache Poisoned Denial of Service (CPDoS) family of vulnerabilities; see
[CPDoS](https://cpdos.org/).  However, it appears we are not
vulnerable, so document the rationale.
=> Document why CPDoS is not an issue

doc/security.md
The GitHub page on its dependency analysis service has moved,
and dependabot is now active. Modify the documentation
to highlight this.
=> doc/security.md: Update info on handling dependencies

.rubocop.yml, CONTRIBUTING.md, lib/tasks/default.rake, script/report_code_statistics
This re-enables the use of the "railroader" static analyzer.
Unfortunately "gem install" doesn't honor Gemfile.lock, only Gemfile.
Implement some workarounds so we can get this working again.
(The intent is to have a cleaner approach longer-term, but we
want to get this working *now*).
=> Re-enable railroader static analyzer

app/views/projects/new.html.erb, config/locales/en.yml
This modifies the "create new badge entry" screen to
display a "don't spam us" message. I suspect many spammers
won't care, but some might, and it's a cheap way to
discourage spammers.
I've included technical text about ugc and nofollow for two reasons:
1. the technically savvy spammers will realize that
we're not worth spamming, *and*
2. the technically savvy NON-spammers will see that
we're trying to fight spam (and will appreciate us for that).
=> Show a "don't spam us" message in new badge entry

app/controllers/account_activations_controller.rb
Local login delay is recorded in seconds, but displayed in hours.
Add the forgotten "divide by 3600".
=> When showing delay convert seconds to hours

lib/tasks/default.rake
We removed railroader because of problems running it.
Now that we can run it again, restore it to the set of
checks run on CircleCI.
In the longer term we move all of this to its own container,
but let's get the checks in use for now.
=> Restore railroader to the set of checks run on CircleCI

app/mailers/user_mailer.rb
Intentionally add a delay when sending activation emails
to counter spammers. The delay time is configurable
with an environment variable.
=> Delay activation email to counter spammers

app/mailers/application_mailer.rb
Sendgrid has various email trackers we don't want enabled, and
some of them are enabled by default (!).  We had previously expressly
disabled click tracking ("clicktrack").
This commit expressly disables ganalytics, subscriptiontrack, and
opentrack, in addition to clicktrack (which was already disabled).
For more information see:
https://sendgrid.com/docs/ui/account-and-settings/tracking/
https://sendgrid.com/docs/for-developers/sending-email/smtp-filters/
https://sendgrid.com/docs/for-developers/sending-email/building-an-x-smtpapi-header/
=> Maximize email privacy

config/locales/en.yml
We've intentionally added a short delay after signing in before
the user receives the activation link.
This commit specifically mentions that delay to the user, so that the
user won't be surprised by that.  It also mentions why the delay
(it's an anti-spam measure). That should reduce the annoyance level of
real users, and it may help discourage spammers.
=> Modify new_activation_link_created to note delay

app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, test/mailers/user_mailer_test.rb
Sendgrid uses X-SMTPAPI in ways we depend on, in particular,
we want to forcibly disable clicktracking and ask for a
delay in sending activation emails.
This refactors the calculation of X-SMTPAPI to make it
easier to query/test, and adds tests for the value of
X-SMTPAPI in some sample emails.
=> Refactor X-SMTPAPI and add tests for it

doc/security.md
Modify doc/security.md to make it clear that we *expressly*
disable all tracking mechanisms we know of in all emails
we send. While we're at it, make a few other improvements.
=> doc/security.md: Add explanation about email

doc/security.md
This documents in security.md how we handle omniauth and CVE-2015-9284
I want to remove the GitHub warning about omniauth and CVE-2015-9284,
but before I do, I think it's important to document the issue in
security.md so people won't think we're just ignoring it.
It's also a good example of the complications of the real world :-).
=> Document how we handle omniauth and CVE-2015-9284

CONTRIBUTING.md, CREDITS, doc/security.md, public/.well-known/security.txt
Add .well-known/security.txt as recommended in https://securitytxt.org/
This adds a simplified direct link to the text about how to
report vulnerabilities, to make it easier to get there immediately.
=> Add .well-known/security.txt, fixes #1372

CONTRIBUTING.md, app/controllers/password_resets_controller.rb, doc/security.md
There's a sneaky attack described in the article by John Gracey titled
"Hacking GitHub with Unicode's dotless 'i'" (Nov 28, 2019),
https://eng.getwisdom.io/hacking-github-with-unicode-dotless-i/
Basically, if you do case-insensitive matches, but then use the
email address provided by an *attacker* to send the email, you
might send it to the wrong place.
We have *never* been vulnerable to this attack.
Still, someone might wonder if we *are* vulnerable to it.
Clearly document that we aren't vulnerable to it, and add
additional comments to ensure that things stay this way.
=> Document that we send emails to correct place

test/controllers/application_controller_test.rb, test/controllers/password_resets_controller_test.rb, test/controllers/project_stats_controller_test.rb, test/controllers/projects_controller_test.rb, test/controllers/sessions_controller_test.rb, test/controllers/static_pages_controller_test.rb, test/controllers/users_controller_test.rb
ActionController::TestCase is obsolete. The Rails developers want
people to switch to using ActionDispatch::IntegrationTest ; see:
https://github.com/rails/rails/issues/22496
However, this isn't immediately obvious in the code.
We include rails-controller-testing which keeps those tests running.
This commit clearly documents that as a "TODO" we want to
to switch from ActionController::TestCase to ActionDispatch::IntegrationTest ;
this will discourage people from adding tests using the
obsolete interface. It also encourages people to switch tests
to the newer system. Finally, it notes that once we remove all uses of
ActionController::TestCase we can remove the gem rails-controller-testing.
This merely commits comments, instead of "doing" anything.
But clearly documenting what needs to …
=> Document ActionController::TestCase is obsolete

app/controllers/projects_controller.rb, test/integration/project_get_test.rb
The production website is getting crawled using a large number of
malformed requests of the form "?criteria_level,2". E.g.:
at=info method=GET path="/en/projects/188?criteria_level,2"
This commit produces a permanent redirect (301) to point
malformed queries to the correct queries.
That way, the crawler can learn what it SHOULD be querying instead.
If there's something on OUR site that is GENERATING these bad URLs,
I'd like to fix that, but I haven't found anything.
=> Handle malformed criteria level, fixes #1257

app/controllers/projects_controller.rb, app/mailers/report_mailer.rb, app/models/criteria.rb, app/models/project.rb, app/models/project_stat.rb, app/views/project_stats/index.csv.erb, app/views/report_mailer/report_monthly_announcement.html.erb, app/views/report_mailer/report_monthly_announcement.text.erb, db/migrate/20200507141751_add_silver_at.rb, db/migrate/20200508145537_add_first_achieved.rb, db/schema.rb, lib/tasks/default.rake, test/controllers/project_stats_controller_test.rb, test/fixtures/project_stats.yml, test/mailers/report_mailer_test.rb, test/models/project_stat_test.rb, test/models/project_test.rb
In the monthly report, report projects that achieve
higher-level badges.
This was a classic "this will be an easy task" that turned
into more work than expected:
* We never recorded achieving
higher-level badges, so we needed a data migration to
add this information.
* I wanted the field names to be consistent, so we
needed a method to convert level ids/numbers
into field names.
* The previous step made it obvious that using
Criteria.keys() as the way to find level IDs wasn't really
sensible; that should be its own constant, and once that's done,
modifying a few routines like update_prereqs() to use it seemed
appropriate (the new version is clearer than the old one - at
least Rubocop thinks so!).
The whole thing should be clearer & thus less likely to have
defects (it should be easier to …
=> Report achievement of higher badge levels

app/lib/hardened_sites_detective.rb
File app/lib/hardened_sites_detective.rb checks for hardened sites.
However, HTTP field names are case-insensitive, see RFC 2616 section 4.2,
and we weren't compensating for that properly
This commit downcases all HTTP header fields before considering them,
so that HTTP headers can be correctly considered while ignoring case.
This should fix #1253.
=> Match hardened site HTTP headers case insensitive

app/lib/hardened_sites_detective.rb, config/locales/en.yml
This commit removes the X-XSS-Protection from the `hardened_sites`
criterion and its automated checker, and makes it clear that we
*always* check for the key hardening HTTP headers.
There are two problems. The first is that X-XSS-Protection has not
aged well. It's supposed to enable some heuristic protections. These
protections are largely unnecessary in modern browsers (CSP is
recommended instead), and it's increasingly obvious that this header
will never be standardized. Firefox won't add it, Edge has retired it.
Perhaps most importantly, securityheaders.io doesn't even report the
status of X-XSS-Protection, making it suddenly harder to see this
header value for a site... and also providing additional evidence that
X-XSS-Protection has outlived its purpose. Details here: …
=> Remove x-xss-protection hardening criterion, fixes #1426

lib/tasks/default.rake
Error seen twice on https://github.com/coreinfrastructure/best-practices-badge/commit/c55ce8fa5c857d5de3cb043c3ab39a6a5348c964
=> Fix incorrect target blank from Google translate

config/locales/en.yml
Improve the hash text further. In particular, add Oxford commas
(for clarity) and add the terms "inbound/outbound authentication"
since this terminology is used elsewhere (e.g., in CWE text).
=> Tweak hash text further

app/controllers/projects_controller.rb
This commit changes CDN purging of badge data to be last.
We've received two reports where an edit of project data worked,
but the badge image display has the old value.
Jason Dossett & I believe the problem is some sort of race condition
with Fastly, but we've not been able to reproduce it.
This moves CDN purges to be the last task done, which should
reduce the likelihood of triggering the race condition.
Before, in the save-after-edit case, there was nontrivial functionality
after a badge purge, making race conditions more likley.
This commit doesn't actually *fix* the race condition, but it should
significantly reduce the likelihood of it occurring, and that's a good thing.
=> Purge CDN last

app/controllers/projects_controller.rb
Send CDN purge early to counter potential delays within the CDN.
When the project is about to be edited, send the CDN a purge request
early as well as late. This increases the likelihood that a purge
will complete before a request is sent if it takes significant time
for the CDN to distribute that information through its internal network.
We continue to send the purge request late, so that if the CDN manages
to get in a request after the early purge but before the change occurs,
the CDN will throw it away.
=> Send CDN purge early, as well as late

app/controllers/projects_controller.rb
Purge the badge image *last* from the CDN.
In a race condition the badge image is the most likely to be
requested, so by requesting it last we reduce the time a
race condition can occur (and thus reduce the likelihood of it).
=> Purge badge image last from CDN

config/locales/en.yml
This *actually* updates the URL for the per-file SPDX license
expression page.  Commit 15a670ccd633b5ffb68d7963639bb5c79f82fe3b
from Steve Winslow tried to do that, but it only modified other.md,u
and did *not* modify the file used when displaying the form.
=> *Actually* Update URL for SPDX license identifiers page

doc/send-translations.rb
Clean up script send-translations so that it's much easier to
use and more generalized. This way, we can easily update our
translations directly from the YAML files whenver that's convenient.
=> Generalize script send-translations

app/controllers/projects_controller.rb, app/models/project.rb, doc/api.md, test/controllers/projects_controller_test.rb
To simplify dashboard use, add a new url= query parameter
that *specifically* searches URLs (this matches
either the home page URL or the repository URL).
If we add package URLs, we would search them as well.
We don't need to add a new index, because both of these
columns are already indexed.
=> Add url= query to /projects

doc/implementation.md, lib/tasks/default.rake
Add the ability for the BadgeApp admin to more easily search on
user email and user name. This is primarily so that we can easily
support GDPR requests, though it can have other uses.
The name search is relatively slow; instead of being indexed,
we look for internal matches while downcasing. But this is a
rare event that cannot be requested by unauthorized users,
so it doesn't matter. It's only *relatively* slow anyway; the
search happens entirely within the database.
=> Enable admin CLI search of email and name (for GDPR)

config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
Add the ability to set the environment variable RAILS_CACHE_SIZE
to control the cache size in Mebibytes (default 128 Mebibytes;
the old default was 64 Mebibytes). Warning: the Rails ".megabytes"
actually means Mebibytes.
I tried merging this into a single initializer, but that caused
test failures. I believe the problem is that that initializing the
cache is especially order-dependent (which makes sense, because it
affects so many other things). I'm sure I could track that down,
but trying to eliminate the duplication of a single simple line
isn't worth the trouble (especially since it was already duplicated).
=> Add ability to control cache size

app/controllers/criteria_controller.rb, app/views/criteria/_one_level.html.erb, app/views/criteria/index.html.erb, app/views/criteria/show.html.erb, doc/criteria-header.markdown, doc/criteria.md, test/controllers/criteria_controller_test.rb
Add `autofill=true` as an option to /criteria displays, so that
this information is much easier to retrieve.
This is in support of OpenSSF discussions.
=> Add ability to show autofill entries

doc/implementation.md
We implement one of the two common mechanisms for countering
memory bloat, but never documented it.
This commits adds some documentation. At the least it will help
people who want to learn more, because otherwise they'll start
researching what we've already researched.
=> Add documentation about memory use

app/controllers/projects_controller.rb
Use .ids instead of .map(&:id) to get a list of ids.
It's clearer *and* more efficient.
=> Minor tweak: use .ids in projects_controller

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/projects/index.html.erb, app/views/static_pages/robots.text.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/initializers/i18n.rb, config/initializers/pagy.rb
This commit changes how we paginate project lists when they're being
displayed. This switches from the will_paginate gem to the pagy gem
to speed view generation, use less memory, and use less code.
The will_paginate gem works, but the article
["Speeding Up Your Ruby on Rails App" by Daniel Lempesis](https://medium.com/@daniellempesis/speeding-up-your-ruby-on-rails-app-4c37ec71b126)
noted that while this was common, the
[pagy gem](https://github.com/ddnexus/pagy) was a significantly
better option. It's much faster and uses significantly less memory.
It's also just cleaner (in my opinion).
Although pagy works differently, switching looked pretty easy, and it was.
The tweak to the robots.txt file isn't strictly necessary, since that's
only needed if we use the JavaScript versions. But it …
=> Switch gems from will_paginate pagy, fixes #1480

Gemfile
Simplify the Gemfile code that automatically loads the Ruby
version as specified in .ruby-version.
=> Simplify Gemfile reference to .ruby-version

Gemfile, Gemfile.lock, config/application.rb
Modify the Gemfile so we *only* load the Rails gems we use.
This reduces our memory use and attack surface.
Previously in our Gemfile we just used this construct to load Rails:
> gem 'rails', '5.2.4.4' # Our web framework
However, that brings in some Rails gems that we never use.
Bringing in unused gems can be a problem.
[Rails issue #36963, "Rails 6.0.0 performance regression because of ActionText::Engine hook"](https://github.com/rails/rails/issues/36963)
discusses a serious problem when using Rails 6 - ActionText
takes a lot more memory (so much that many people have reverted
an upgrade). We don't plan to use ActionText anyway;
it fails to support markdown.
ActionText builds on Trix, and we have requested markdown suport
([Trix issue #626](https://github.com/basecamp/trix/issues/626)) …
=> Gemfile: Break rails gem into selected dependencies

app/controllers/badge_static_controller.rb, app/controllers/projects_controller.rb, app/helpers/badge_static_helper.rb, app/models/badge.rb, app/models/project.rb, config/routes.rb, test/controllers/badge_static_controller_test.rb
Add a new /badge_static/:value route; this serves *static* SVG
badge images given just "value". Value can be 0..99, passing,
silver, or gold. This will be cached by the CDN (Fastly).
This is the first step in implementing some countermeasures against
CDN race conditions. The plan is to use this to
serve /:locale/projects/:number badge entries. That way, if the
badge entry has just changed, but the CDN hasn't caught up yet, the
user who just change the project data will nevertheless
see the *current* status of the project.
We could also do this with the /projects display.
We still want projects, on their README, to use the
/projects/:number/badge URL when displaying badges, because that
will automatically adjust as the project's badge status changes.
Signed-off-by: David A. Wheeler …
=> Add a new /badge_static/:value route

app/controllers/projects_controller.rb, config/initializers/cors.rb, doc/api.md, test/controllers/projects_controller_test.rb
We need to add rate limits to counter overeager spidering tools
*without* impacting legitimate users. Some users (e.g., dashboards)
want to provides lots of data about project status.
We already use our CDN (Fastly) to cache the badge SVG.
This commit *also* caches the badge JSON data on our CDN.
That will let us support many more requests for badge JSON data.
The actual code change is tiny, but this adds many comments.
I had to do quite a bit a research about caches and CORS to
gain confidence that this wouldn't have some subtle problem in practice.
In the process, I discovered that our support for the
HTTP header 'Accept:' looks nice in theory, but in practice
creates complications. So I documented that we want people to use
different URLs with different suffixes to request different …
=> Cache badge on CDN in JSON (in addition to SVG)

.github/workflows/main.yml
Create a .github/workflows/main.yml file and use it to
call Brakeman to do static analysis
Almost all of our CI pipeline runs on CircleCI.
However, GitHub actions provides a convenient way to run Brakeman,
a static analysis tool for Ruby on Rails applications.
There's no reason we can't use both, and I want to quicky
re-add Brakeman. We can move Brakeman to CircleCI later if
that's important.
This uses our credential, but note that we do NOT check in
the credential into version control (that would be bad!).
That does raise the question of whether not we trust the tool
and the GitHub action shim to call it.
GitHub themselves use Rails, so while I don't know devmasx
personally, I think GitHub's vetting is adequate for us to trust it.
Brakeman's license allows us to use it, but it is no …
=> Add Brakeman GitHub action

app/views/users/show.html.erb, config/locales/en.yml
Thanks to COVID-19, people often share screens with others.
This commit removes the screen display of email addresses on user display,
even to those authorized to see it. Instead, it just shows "Send email"
as the text. We continue to support a mailto: hyperlink.
No functionality is lost, this commit just reduces the risk of
unintentional disclosure via screen sharing.
Those who are authorized to see the email addresses can still
hover to see it, or click on the link to send an email, or
right-click to copy the email address.
We also still display the email address if a user is *editing* their
entry. But editing is a much rarer event, and we *have* to display
the email address then (so users can confirm it and/or edit it
to the correct value).
Signed-off-by: David A. Wheeler …
=> Do not display email address in user display

app/controllers/projects_controller.rb, app/lib/chief.rb
Modify error logging:
* Add an "ERROR:: " term to make it easier to search for error reports.
* Switch to a block, so that logging strings are only computed
when needed. Currently this won't matter, but it might in the future.
=> Improve error log reporting

config/initializers/rack_attack.rb, doc/api.md, doc/best-practices.py
Add a separate rate limit for anything other than badge images
that is significantly lower than the "any request" rate limit.
Some badly-behaved crawlers/spiders/scrapers abuse the website
and request "everything at once".  We can handle badge images requests
more easily (they're fast and the CDN handles most of the load),
and we *expect* many badge image requests. However, we don't expect
other requests quite as much. Making too many of those requests can
result in denial of service, and the system burden also makes it harder
to serve others in a timely way.
By adding a separate rate limit, and one that triggers much more quickly
(before we even hit the number of active threads), we quickly halt
any unintentional overload and we quickly signal to crawlers that
they need to be patient. …
=> Add non-badge-image rate limit, fixes #1475

config/initializers/pagy.rb
By default pagy raises an exception if the page# is too large, which
has a lot of overhead for a common circumstance. Instead,
just show an empty page if it's empty.
=> Show empty page if page# too large

app/views/projects/index.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
If there's only one page of results, omit the page navigation
material. It just adds clutter without purpose in that case.
=> If there's only 1 page, don't show page navigation

README.md
I like the idea of using two different licensing check tools, including
the one done by FOSSA (fossa.io).  However, the actual FOSSA service
is causing us problems.  It's incorrectly giving a failing report because
it can't find some licenses. By itself that'd be fine if we could
override its false results; no tool can be perfect.  However, although I
can log in to their service, I can't seem to override the false positives.
Licensing is important, but we *already* use a tool
(license_finder) to analyze our licenses to help us meet them all.
We don't *need* to use multiple tools, especially one that has caused
problems. The license_finder tool provides lots of information, and
provides a clear way to override incorrect results while documenting
every override (including why the result is …
=> Remove FOSSA badge

.circleci/config.yml, Gemfile, Gemfile.lock, dockerfiles/2.7.2-browsers/Dockerfile
CircleCI is now promoting the use of a new set of starting
images in the "cimg" space, designating the ones we used
as "legacy". The newer "cimg" images are built on Ubuntu,
and are supposed to be faster and more deterministic.
See <https://hub.docker.com/r/cimg/ruby>.
This commit:
- creates a new Dockerfile for a special image
that builds on this newer "cimg" format
`dockerfiles/2.7.2-browsers/Dockerfile` that
adds what we need (e.g., cmake).
- Switches to using this newer "cimg" format on CircleCI
for testing and building.
This was *incredibly* painful to achieve, and took *much*
longer than it should have taken.
CircleCI strongerly recommends using the browser-tools orb.
However, I never got that to work in spite of endless tweaking.
I ended up creating a special task to install a …
=> Switch test env to CircleCI cimg

app/views/layouts/_header.html.erb, config/locales/en.yml, config/locales/translation.de.yml, config/locales/translation.es.yml, config/locales/translation.fr.yml, config/locales/translation.ja.yml, config/locales/translation.ru.yml, config/locales/translation.sw.yml, config/locales/translation.zh-CN.yml
Modify how the locale list at the top is generated
to simplify its translation.
Originally we had exactly one string per line, reducing the
string-handling necessary to generate the locale list
(string handling always has some small performance overhead).
However, this approach required every translator to insert text from
other locales, and that is very error-prone.
This changes the locale list so that translators only need to
translate locales (language names) for their own locale.
The system will automatically extract the locale name in those
other locales and the system locale name. This is much
less error-prone. The locale list is cached, so avoiding the
extra string handling doesn't really save any performance either.
=> Simplify translation of locale list

Gemfile, app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/lib/fastly_rails.rb, app/models/application_record.rb, config/initializers/fastly.rb, test/controllers/users_controller_test.rb, test/features/login_test.rb, test/unit/lib/fastly_rails_test.rb, test/vcr_cassettes/fastly_no_key.yml
The gem "fastly-rails" does not work on Rails 6, so we
must eliminate it to upgrade to Rails 6.
They recommend switching to the "fastly" gem (aka "fastly-ruby"),
but fastly-ruby is not designed to support multi-threading (WHAT?!).
The only workable solution I could find was to modify our code
to directly call the Fastly API instead.
This turned out to be more complicated than expected, and
frankly was a big pain. However, this is a blocker to upgrading
Rails, and the version of Rails we use is no longer supported,
so this needed to be done.
We need to test this on the *real* system to ensure that it really works.
=> Remove gem fastly-rails

app/views/layouts/application.html.erb
The logo should be identified as an image path with its extension.
=> Fix logo path

app/controllers/application_controller.rb
We need to send cookies while logged in so that /logout
will work properly (it's needed for a CSRF countermeasure).
=> Send cookies while logged in

config/locales/en.yml
US export control law has some quirky requirements about
encryption that are easy to comply with, but have potentially
harsh penalties for non-compliance. Mention them in the crypto
section, since many developers won't know about this legal requirement,
as a way to help out the developers.
=> Mention US export control law; fixes #1513

.circleci/config.yml, doc/testing.md, test/application_system_test_case.rb, test/system/examples_test.rb
Implement the standard Rails system test via its conventional
configuration file test/application_system_test_case.rb
and create a first system test (test/system/examples_test.rb)
using this Rails system test framework.
This required various modifications to actually work.
In particular, modern Chrome *requires* disabling the sandbox for the
system tests to work, and we need to configure it to be headless.
Warning! By default "rails test" (and thus rake) do *NOT* run system tests.
You must run system tests via "rails test:system". To run *both*
system and non-system tests, say "rails test:system test" (in that order).
This commit modifies our CI pipeline so that it runs BOTH
system and non-system tests. So for most people this detail will be quietly
handled correctly. Rails 6.1 adds …
=> Create Rails system test stub

config/initializers/translation.rb, config/locales/en.yml
Add pt_BR (Brazilian Portuguese) as a translation target.
This does *not* allow selecting it from the run-time menu;
that will be a separate pull request once we have some
actual translated text.
=> Add pt_BR (Brazilian Portuguese)

test/models/translations_test.rb
I found that it's easy to accidentally use a "_" instead of "-"
in locale keys, which leads to problems.
This commit adds some sanity self-tests about the locale keys, so that
problems like "invalid locale key syntax" and "mismatched lists"
will be detected by our test suite.
=> Add self-test of locale ids

Gemfile, Gemfile.lock, test/controllers/projects_controller_test.rb, test/system/github_login_test.rb, test/system/github_project_test.rb, test/system/github_user_test.rb, test/unit/lib/rake_task_test.rb
Remove the gem database_cleaner, as we should not need it any more.
In general this works. However, this currently produces a
flapping test that sometimes, but inconsistently, produces this error:
Running tests with run options --seed 46922:
Failure:
ProjectsControllerTest#test_sanity_test_of_reminders [/home/dwheeler/best-practices-badge/test/controllers/projects_controller_test.rb:948]
Minitest::Assertion: Expected: 1
Actual: 0
=> Remove gem database_cleaner

app/controllers/application_controller.rb, doc/implementation.md
Increase the default time that badges are cached
and the default time that badges are served by the CDN when stale.
Also add environment variables to control these values.
The increased default `BADGE_CACHE_MAX_AGE` (from 1 day to 10 days)
reduces server effort. Badge responses are very fast, but
it's even faster when we don't have to deal with them at all.
The current (1 day) setting means that in practice every day
we must reply a badge for every single project. We don't need to do
that; let's distribute the work further.
The increased `BADGE_CACHE_STALE_AGE` (from 10 days to 100 days)
provides us with greater protection from server problems.
If the server goes down, badges will continue to be served for a
long period of time, so many people won't even realize we're down.
We can purge …
=> Increase badge cache time & add control

app/controllers/application_controller.rb, test/controllers/project_stats_controller_test.rb
We want *stop* listening to the "Accept" header, but is anyone using it?
This logs anything interpreted as a JSON request but has a .json
extension, to help detect those using an obsolete request.
=> Log JSON requests without .json suffix

config/initializers/cors.rb, doc/api.md, test/controllers/project_stats_controller_test.rb
Ignore the HTTP 'Accept' parameter when serving pages.
Instead, to choose a different format, use a different URL.
Our API documentation had previously deprecated the 'Accept'
parameter; this commit actually eliminates the deprecated mechanism.
We do *not* want to use the HTTP Accept header to decide what format to send,
because that interferes with using the CDN. Without this setting,
Rails will produce different values (in some cases) depending on the
HTTP "Accept" value, and thus will generate "Vary: Accept" (correctly).
However, since different browsers will have
different Accept header values, this Vary: Accept will mean that
different browsers will not share a CDN cached value.
By setting ignore_accept_user, users *must* use the URL to request a
non-default format. In compensation, …
=> Ignore HTTP 'Accept' parameter

app/controllers/project_stats_controller.rb, test/controllers/project_stats_controller_test.rb
If we just set the HTTP header 'Cache-Control', Rails quietly
adds "private" which we do *NOT* want when showing project_stats.
So, switch to using Rails' expires_in, where we can easily set
public: true.
This should significantly optimize project_stats views, because it
allows the JSON files to be cached by the CDN (as was intended).
=> Use expires_in to show project_stats

app/controllers/application_controller.rb
Our caching wasn't working well because we set
max_age but that should have been max-age.
Fixed.
=> Fix: max_age should be max-age

config/initializers/cors.rb, test/controllers/projects_controller_test.rb
The CORS patterns were defined with strings (globs). Those are
easy to read but in some cases the patterns overlapped.
The overlap meant that some .json files were being incorrectly sent
with a "Vary" over Origin, which interferes with caching.
There doesn't seem to be a way to prioritize the patterns to
prevent this as long as we stick with globs.
This commit redefines the CORS patterns with regexes.
Regexes are more complicated, but far more powerful; we can
use regexes to far more precisely declare the patterns.
As a result, the .json endpoints will no longer Vary by Origin,
which should significantly improve caching.
The final outcome is that this commit should increase average
user speed AND reduce average server load, both due to
better caching. It's always nice to get both. …
=> Redefine CORS patterns using regexes

app/controllers/badge_static_controller.rb, config/routes.rb, test/controllers/projects_controller_test.rb
Add various validations to the router so it's pickier about
what it accepts. In particular, IDs must be positive integers.
Before we quietly converted IDs that *started* as integers
as integers, but we have attackers creatively adding garbage
after the ID to try to trigger attacks. We know of no way for
that to actually *work* as an attack on our system, but it's
better to validate input and reject anything that doesn't meet
our strict criteria. We do that in other places; now we'll make
these pickier as well.
=> Make app router validations pickier

config/initializers/rack_attack.rb
We're getting a lot of attacks of the form
/:locale/projects/:id followed by a % or & and then nonsense.
These are *legal* URLs (per the URL spec), but there's
no reason to send paths with that pattern to our site;
they simply seem to be attacks. They're naive attacks and
seem unlikely to break into the system, but since we can
detect them as attacks, let's tweak our default FAIL2BAN
pattern to counter them. This reduces the time we waste
responding to them, and might also prevent a real attack
(they might later randomly find a *working* attack, but if
we've already temporarily banned them it would be ignored).
=> Extend default FAIL2BAN pattern for % or &.

app/views/static_pages/robots.text.erb
URLs with /projects*[&%] can sometimes indicate attacks,
and there's no need to crawl them.
By including this in the robots.txt file, we can help
web crawlers not look like attackers.
=> Modify robots.txt to disallow /projects*[&%]

app/controllers/projects_controller.rb
When querying /:locale/projects.json we include additional_rights.
This commit adds an ".includes" to eliminate the N+1 query
that otherwise results from that, improving performance.
=> Remove N+1 query in /:locale/projects.json

app/controllers/application_controller.rb, app/views/project_stats/index.html.erb
Provide the link to the CSV and JSON project stats
*without* a locale, and allow CSV to skip locale redirects
(like JSON already does). This means that we can can
have our CDN cache those values regardless of locale...
reducing the likelihood of doing it, and increasing speed
of response in cases where more than one person sent the
request (even if those users use different locales).
=> Provide locale-less CSV/JSON project stats

.circleci/config.yml, CONTRIBUTING.md, lib/tasks/default.rake
Rename the "master" branch to "main" in git.
This does *not* change the Heroku app name. That is *much*
more complicated because renaming that requires new certificates,
as well as modifications of settings in Scout APM, Heroku, and
several Heroku plugins at least, it will require new DNS entries
and a re-authentication with SendGrid, and possibly other changes
that we aren't sure we understand.
It is less risky to try to do this rename in stages, so that's
what we're doing.  In addition, the Heroku name is a lot less visible.
=> Rename "master" branch to "main"

app/models/project.rb
This commit caps the "percentage" value to
99 at most if the level is not 100% complete.
This is a defensive programming measure.
We round percentages, so this will only a problem once
(N-1)/N >= 0.995, that is, number of items in a level N>=200,
and we don't want that many questions in a level.
Still, I feel better being *certain* it cannot cause problems.
=> Make percentage <100% if level incomplete

test/fixtures/projects.yml, test/integration/recalc_test.rb, test/models/project_test.rb
The test fixtures for projects didn't have the correct
percentages; when they were later recalculated to correct
values the result was flapping tests.
This fixes the test fixtures for projects, and adds tests
to specifically detect this kind of problem in the future.
=> Fix test fixture project percentages

app/lib/fastly_rails.rb, lib/tasks/default.rake, test/unit/lib/fastly_rails_test.rb
Update `rake fastly:purge_all` to work properly.
We previously had to remove the FastlyRails gem, but
never changed how to do a `purge_all`, so that rake command
no longer works.
This commit re-implements purge_all so that it works again
(and renames it from `purge` to `purge_all` to clarify that
is what it's doing). We must `purge_all` when, for example,
there's a change in how the badges are calculated (so that
recipients will see the new results).
Sadly, due to a limitation of Fastly's API,
we *cannot* do a soft purge, aka "Fastly-Soft-Purge: 1".
A soft purge would let the CDN distribute the cached value
if it couldn't contact the real server. Unfortunately,
Fastly doesn't support soft purges on full purges.
Beware: Do *not* run `purge_all` lightly on real systems.
It will temporarily …
=> Update Fastly purge_all

doc/best_practices_modify.py
If the user makes a CLI error, explain it briefly and
remind them that they can use --help for more information.
=> doc/best_practices_modify.py: remind about --help

app/views/static_pages/criteria_stats.html.erb
Replace the only case of hardcoded ['0', '1', '2'] with
`Project::LEVEL_IDS`.
*Currently* this doesn't matter, because
we only have 3 level ids (corresponding to passing, silver, & gold).
However, if we ever add additional levels (such platinum), we want
to be able to add that information in very few places, and for the
rest of the code to just automatically work correctly.
To do that, we need to eliminate all hardcoding of level ID lists,
and instead refer to standard value - which is `Project::LEVEL_IDS`
defined in `app/models/project.rb`. I've only found this one case
where we hardcoded values, and it'd be best to fix it now.
=> Eliminate hardcoded list of level IDs

doc/implementation.md, lib/tasks/default.rake
When the LF gets GDPR requests to erase user data, we
must search the CII Best Practices database.
This commit makes searching simpler and faster, by creating a new
`rake search_user NAME EMAIL` command that can search for
*both* name and email in a single command. Most of the time we
get a single name and email address in each request, and it takes
a while to spin up the rake task, so this way we get all the answers
for a single user at once.
=> Add rake task "search_user" to simplify GDPR requests

Gemfile, Gemfile.lock
Update gems bullet (6.1.3->6.1.4) and
minitest-retry (0.2.1->0.2.2).
=> Update gems bullet and minitest-retry

doc/other.md
The term "killed" is overly specific and morbid, especially since the sentiment here applies to loss of support for any reason, such as someone simply discontinuing involvement with the project.
Signed-off-by: Cary Phillips <cary@ilm.com>
=> Rephrase continuity section with less morbid language

criteria/criteria.yml, doc/nyc-2016.md, doc/other.md
The old URL for Peter Miller's "Recursive Make Considered Harmful"
no longer works. Replace the URL with fixed version provided by
archive.org. Sadly, Peter Miller died on 2014-07-27, but his
good ideas live on.
=> Update URL for "Recursive Make Considered Harmful"

README.md, config/locales/en.yml
Note that this project is now part of the OpenSSF.
The CII officially has ended, and it's been succeeded by the
Open Source Security Foundation (OpenSSF).
I meant to do this earlier, but in the process of adding information
on the CII website I noticed that this hadn't been done.
So, let's fix it!
For some people this may not *matter*, but it's generally good
to note "where this project fits in" where it's part of
something larger.
=> Note OpenSSF!

config/locales/.translation_io
Record a timestamp for "rake translation:sync".
When we change English text that is to be translated,
we need to synchronize that with the dataset at transiation.io
so that our translators can translate.
This records the timestamp so that later translation:syncs
will know that our database is synchronized to this date.
=> Timestamp rake translation:sync

CONTRIBUTING.md
Sadly Dan Kohn has passed away, so we need to remove him as
a security contact.
Rest in peace, Dan. You are missed.
=> Remove Dan Kohn as a security contact

.github/dependabot.yml
It's possible to enable dependabot via just GitHub project settings,
and we did that for a while. However, when a project does that,
it's harder for others (such as OpenSSF Scorecard) to realize or verify
that the project has dependabot enabled. Creating this dependabot.yml
file makes easier to *verify* that automatic dependency update proposals
are happening. This also gives finer-grained control.
=> Add .github/.dependabot.yml

.github/workflows/main.yml
Limit the privileges granted to our GitHub Action workflow
to just the subset required.
This was flagged by Scorecard. See:
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
More information about GitHub Actions permissions are here:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
This sets "permissions" with a restrictive set of permissions.
Anything unset has access "none" once "permissions" is set.
Hopefully none of the code in GitHub actions is malicious or has
an unintentional vulnerability that can be exploited in this context.
However, it's better to limit privileges so that even if there *is*
a vulnerability, the damage is highly constrained.
=> Limit privileges of GitHub Actions workflow

lib/tasks/default.rake
Validate the email address when calling search_email or search_user.
When we get GDPR requests we search for names and email addresses,
often by calling search_name,  This command requires that you
list the name and then email address.We don't want to allow
accidental swapping of email and then name, as we wouldn't find
data if it *is* there. To greatly reduce the likelihood of this
user error, do a simple validation of email addresses
and raise an exception if it fails.
The validation could be more sophisticated, but it's unlikely names
include '@', so just checking for an '@' with at least one character
around it should be sufficient. We can't prevent all user errors;
this just makes it much more likely to be detected.
=> Validate email on search_email / search_user

.circleci/config.yml
Have CircleCI call "rake bundle_audit" so the bundle audit
configuration is in a single place.
=> Tweak CircleCI to use rake bundle_audit

config/locales/localization.pt-BR.yml
This checks in file "config/locales/localization.pt-BR.yml".
We've had this file for some time, but didn't check it in
accidentally so it's not been posted. Thankfully the effects are
subtle, but they're unintended; let's fix that.
=> Check in config/locales/localization.pt-BR.yml

doc/api.md, doc/governance.md, doc/vetting.md
Modify several .md files to rename CII to OpenSSF.
=> Modify some doc/*.md files to rename CII->OpenSSF

Gemfile, Gemfile.lock, config/initializers/pagy.rb
Update the pagination gem pagy from 4.11.0 to 5.9.1.
This update was delayed because of breaking changes in the
transition from pagy 4.X to 5.X. I'm not a fan of breaking changes,
but to be fair, when we followed the directions in:
https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md#version-500
the upgrade was quite smooth.
=> Update gem pagy 4.11.0->5.9.1

.github/workflows/main.yml
Dependabot automatically creates update changes,
but doesn't fix the comments that explain what pin is to.
Fix the comment to match hash value.
=> Fix github actions/checkout pin comment

Gemfile, Gemfile.lock
Dependabot tried to do this in #1755 but its approach didn't work.
=> Bump minitest-reporters from 1.4.3 to 1.5.0

db/migrate/20220203172721_add_blocked_to_users.rb, db/schema.rb
This adds "blocked" and "blocked_rationale" fields to the users table.
Unfortunately some users choose to create fraudulent entries.
They're rare, but when it happens we want to block them
from being able to change anything, and record why.
This commit *only* modifies the schema so we can record this
information - it does not *enforce* them. I'm creating them as
separate commits so that we can record this information immediately.
We can then later add the code to use this information to enforce it.
=> Add "blocked" field to users table

app/validators/url_validator.rb
Allow tilde (~) in project URLs, fixes #1780.
We're intentionally restrictive in project URLs.
However, projects hosted on [SourceHut](https://sourcehut.org/)
use URLs in the format
https://git.sr.ht/~username/repo
So we need to allow tilde (~).
Here's a test case:
https://git.sr.ht/~emersion/annotatesh
=> Allow tilde (~) in project URLs, fixes #1780

.github/workflows/main.yml
=> Fix: rename master->main in GitHub workflow

.circleci/config.yml
This comment switches from ssh git transport to HTTPS
transport when sending the code update to heroku.
Heroku has deprecated ssh git transport, so it requires
using HTTP instead of SSH. In particular, they've turned off
the ssh server for it:
https://devcenter.heroku.com/changelog-items/2215
As a result, we must modify the deployment script to stop
using the ssh git transport, and instead use these instructions:
https://devcenter.heroku.com/articles/git#deploy-your-code
=> Stop using git ssh on heroku

.circleci/config.yml
"heroku login" won't set up .netrc from the environment variable,
so we have to do it by hand.
=> Login to heroku (set up .netrc) - another try

bin/rails, bin/rake, bin/spring
We repeatedly were getting the warning
"Array values in the parameter to `Gem.paths=` are deprecated".
The problem involves the `spring` gem. For details, see:
- https://stackoverflow.com/questions/37864054/rails-5-array-values-in-the-parameter-to-gem-paths-are-deprecated
- https://github.com/rubygems/rubygems/issues/1551
The solution is to run these commands and check in the result:
~~~~sh
bundle update spring
bundle exec spring binstub --remove --all
bundle exec spring binstub --all
~~~~
=> Fix Array values in the parameter to `Gem.paths=` are deprecated

Gemfile.lock
Update the transitive dependencies by running `bundle update`.
This bumps `rack` from 2.2.3 to 2.2.3.1, repairing
[CVE-2022-30123](https://github.com/advisories/GHSA-wq4h-7r42-5hrr).
This is a shell escape sequence injection vulnerability in the Lint
and CommonLogger components of Rack.
The problem is that carefully crafted requests can cause shell escape
sequences to be written to the terminal via Rack's Lint middleware and
CommonLogger middleware. These escape sequences can be leveraged to
possibly execute commands in the victim's terminal.
We probably aren't vulnerable to this. Known attacks only apply when
`Rack::Lint` or `Rack::CommonLogger` are used, and a `grep -R`
finds neither. However, our general policy is to simply update
if there's a security vulnerability in our components …
=> Update transitive dependencies (`bundle update`)

config/locales/en.yml
Note on the front page the official rename date.
This is worded so that someone searching for the exact
phrase "CII Best Practices badge" *will* find a match
on the front page, and thus helping people find it.
=> Add rename date from "CII Best Practices badge"

doc/security.md
We basically show the top level twice - explain that.
=> Clarify that currently only top level shows SACM

app/models/project.rb
Harden the method projects_first_in to ensure there's no
SQL injection vulnerability.
Method projects_first_in uses a parameter to create a
SQL query. That parameter should already have been tested by
this point, but Brakeman (at least) can't confirm that,
and if the code changed this could become a security vulnerability.
So instead, first check if "level" is one of the short list
of valid values. That will prevent this from becoming a SQL
injection *even if* level can be somehow set by an attacker.
We can't use use SQL parameterized statements here because the
field names are getting created at run time, and parameterized
statements typically have trouble with field names created at run time.
=> Harden projects_first_in

app/controllers/password_resets_controller.rb, config/locales/en.yml, test/controllers/password_resets_controller_test.rb, test/integration/password_resets_test.rb
Previously we replied with error reports if there was no account or if
there was a GitHub account (not a local account) with the email address.
However, that allowed attackers to determine if a given email address
was present or not in an account. That's not a large leak of
information; the attacker has to already guess the specific email address,
and they merely get "is present/absent" instead of the specific account.
Many systems *do* provide such error messages, so many users would
be unsurprised by this information leak.
Still, we want to be excellent at providing user privacy, so we're
going to go beyond what some might see as the minimum, and instead
do what we can to maximize our users' privacy.
We previously made a similar change to prevent leaking the presence
or absence of an …
=> Make password resets *always* reply same message

app/controllers/password_resets_controller.rb, test/controllers/password_resets_controller_test.rb
Once a password reset has been sent, wait at least
DELAY_BETWEEN_RESET_PASSWORDS before sending another so attackers
can't badger our users with password reset requests.
Note that this adds a test to verify this.
=> Add DELAY_BETWEEN_RESET_PASSWORDS

CODE_OF_CONDUCT.md
We are now an OpenSSF project, so we need to apply the OpenSSF
Code of Conduct (CoC). This project predates the OpenSSF, and when we
added a CoC we used a different CoC from the Linux Foundation.
Now that we *are* part of the OpenSSF, we should have update this. However,
I just realized that I never updated the CoC to match. This fixes that.
We generally haven't had Code of Conduct problems, and the core
*fundamentals* are unchanged: treat everyone else well.
Still, I think it's best to prepare to counter potential problems
ahead-of-time.
The markdown text was created by downloading the text from
<https://openssf.org/community/code-of-conduct/> and then using the
online tool <https://codebeautify.org/html-to-markdown>.
This file *does* link to the OpenSSF CoC page, but I thought it'd be …
=> Update to OpenSSF Code of Conduct (CoC)

doc/security.md
Modify doc/SECURITY.md to document how we protect email addresses
from enumeration.
=> Document how we hide email addresses from enumeration

app/views/projects/_form_early.html.erb
https://bestpractices.coreinfrastructure.org/en says:
> This project was formerly known as the Core Infrastructure Initiative (CII) Best Practices badge. and was originally developed under the CII. It is now part of the [OpenSSF](https://openssf.org/) [Best Practices Working Group (WG)](https://github.com/ossf/wg-best-practices-os-developers). The OpenSSF is a foundation of the [Linux Foundation (LF)](https://www.linuxfoundation.org/). The project was formally renamed from "CII Best Practices badge" on 2021-12-24.
However, the badge templates still have the CII name.
For example at https://bestpractices.coreinfrastructure.org/en/projects/6331 :
> You can show your badge status by embedding this in your markdown file:
`[![CII Best …
=> Rename CII to OpenSSF in badge alt text

.github/workflows/main.yml
GitHub actions doesn't update matching "# pin ..." comments, so update its comment.
=> Fix actions/checkout comment pin

doc/security.md
Fix trailing space in doc/security.md line 716.
=> Fix trailing space in doc/security.md

.circleci/config.yml, doc/INSTALL.md, doc/design.md, doc/implementation.md, doc/security.md
Heroku has eliminated its free services, which we originally used for both our main/master tier and staging tier.
This commit removes the "main/master" tier as a cost-cutting move. We'll still have the "staging" and "production" tiers; use `rake deploy_staging` and `rake deploy_production`  to deploy to those respective tiers. This eliminates the attempt to deploy to the "main/master" tier (which is about to be deleted), as well as updating the documents to reflect this change.
=> Remove `main` tier for deployment

.github/workflows/main.yml
Reverts coreinfrastructure/best-practices-badge#1887
This didn't seem to fix the problem
=> Revert "update main.yml"

SECURITY.md
Provide the OpenSSF security reporting address as an "if all else fails" mechanism. I don't expect that to be the primary mechanism, but the key is to make sure people *can* report vulnerabilities.
=> Add OpenSSF security email address

app/helpers/sessions_helper.rb, docs/implementation.md, test/unit/not_in_development_test.rb
We're transitioning to a new web address.
It would be much easier to move if we didn't use the domain name to determine if we're the "real" site.
=> Use a special env variable to indicate real site

app/mailers/report_mailer.rb, app/views/report_mailer/gained_level.text.erb
Modify the application so it starts using an environment variable for the main hostname, instead of it being built-in.
This will make it easier to move from one to another.
=> Use PUBLIC_HOSTNAME or 'localhost' for some email

config/initializers/secure_headers.rb, test/integration/project_get_test.rb
To transition to a new domain, we need to allow an alternative domain for a period of time. However, for security reasons we specifically harden *against* other domains, so we need to modify our requirements.
=> Modify CSP further to allow alternative domain

config/initializers/secure_headers.rb
This will simplify transitioning to a new domain, by *always* ensuring the old and new domains will be listed as allowed.
=> Support 2 alternative domains

config/initializers/cors.rb
In the transition from bestpractices.coreinfrastructure.org to www.bestpractices.dev we'll have people who are requesting one and will end up getting some from the other. This will result in some cross-origin requests (CORS) for fonts from /assets.
It's *fine* to serve static content across CORS, so let's allow it in all cases.
=> Allow cross-CORS for asset requests

app/views/layouts/application.html.erb
I am trying to determine why users are being redirected when they should *not* be redirected.
When viewing the main page, the URLs are fine until "auto_discovery_link_tag" is called, and from then on the domain name is wrong. My hypothesis: this routine is incorrectly setting a global variable for the hostname, causing later calls to be wrong.
So let's instead force the URL to a local reference, which is fine and eliminates the call entirely. I don't know if this will solve the problem, but this change is harmless, and its results can tell us if we're on the right track.
=> Change how feed view is linked

config/initializers/secure_headers.rb
Allow redirection of forms, or searches in /projects don't work in Chrome.
=> In CSP form_action allow redirections

README.md, SECURITY.md, docs/INSTALL.md, docs/api.md, docs/assurance-case.md, docs/background.md, docs/criteria.md, docs/design.md, docs/governance.md, docs/implementation.md, docs/other.md, docs/requirements.md, docs/roadmap.md, docs/testing.md, docs/vetting.md
It's confusing to have 2 documents named "security.md". Give the assurance case a different name.
=> Rename docs/security.md to docs/assurance-case.md

criteria/criteria.yml, docs/other.md
We credit the "Open-source Maturity Model" in a few places, but it's no longer available at that URL. Use an archive.org link instead, so people who want to track citations can find it.
My thanks to @Darksonn for reporting the broken link!
=> Change the OMM link to use archive.org

app/views/projects/_form_0.html.erb, app/views/projects/_form_1.html.erb, app/views/projects/_form_2.html.erb, app/views/projects/_form_early.html.erb, config/locales/en.yml, docs/criteria.md, docs/dependency_decisions.yml, docs/testing.md
People asked how to show the items to be done, but we've had that functionality for years. Change things as follows:
* Improve button text color contrast
* Move buttons down to make them more obvious
* Change the button text on hiding/showing completed criteria to clarify what is produced.
=> Make it more obvious how to show only the todos

app/controllers/projects_controller.rb, app/views/projects/show_markdown.erb, test/controllers/projects_controller_test.rb
Interpret "no criteria_levels given" as "provide all levels".
=> Markdown generation: no level means all levels

CONTRIBUTING.md, app/views/layouts/_header.html.erb, config/locales/en.yml, docs/TSC.md, docs/governance.md, test/system/access_home_test.rb, test/system/github_login_test.rb, test/system/github_user_test.rb
Clean up various legal/charter constructs.
The Linux Foundation plans to move this project into its own LLC (this provides various legal protections), and we must state that.
A side-effect is that we need to create "Technical Steering Committee" (TSC). I think that's a good thing. I intend to start it with me (as I was the original project lead & committer), and work to add others to it, so it's not just me working by myself.
The proposed approach says the OpenSSF TAC can change the TSC by majority vote. The intent is to ensure that I (or anyone else) can't be a dictator, and that it's possible to get things going again if something goes wrong. Originally I was going to have the OpenSSF Best Practices WG do that vote, but I think it'd be better to have the TAC do it.
=> Create LLC and TSC

app/helpers/projects_helper.rb, app/views/projects/_form_0.html.erb, app/views/projects/_form_1.html.erb, app/views/projects/_form_2.html.erb
Add ids for every section, to make it easy to jump directly to them. Section ids have the form "section_" followed by the English name of the section downcased and with spaces turned into underscores. Only characters A-Za-z0-9_- are used, any other characters are removed.
The "section_" prefix is necessary because there are cases where the section name and the criterion overlap (e.g., `floss_license`).
=> Add section ids to project badge entry

config/initializers/translation.rb
We had a translation.io secret API key checked into the repo. That's a common mistake that's easy to make, but isn't acceptable. This commit fixes this.
That old exposed API key has been revoked, so it cannot do any harm now.  The code has been changed to acquire the key from the environment, so that the key will no longer need to be in the repo.
We have no evidence the exposed translation.io secret API key was ever exploited. That API key is *never* directly used by the production site, and that key cannot affect the English text.
Instead, that secret provides access to the translations of the text, so someone could have changed the English text our translators saw or the translated text they produced. That said, I think our human translators would have complained if they saw weird …
=> Fix translation.io

.circleci/config.yml
Modify the CircleCI configuration so that we test using PostgreSQL 13. We're about to switch from 12->13, and we want to ensure that (1) it works and (2) we make the test environment maximally similar to production.
=> Test on CircleCI using PostgreSQL 13

app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/jobs/application_job.rb, app/jobs/purge_cdn_project_job.rb, app/models/project.rb, test/jobs/purge_cdn_project_job_test.rb
Add a delayed job to purge CDN project data to fix a race condition.
In some cases the CDN can end up with old data due to a race condition between the server and CDN. There doesn't seem to be a reasonable solution to *end* the race. So to solve this, add an additional delayed job to re-purge data for a given project. That way, if the CDN loses the race, the obsolete data will soon be purged and the next request will get the correct data. At worst there will be a few seconds where users see the old data, but that's unsurprising behavior - it will look like it took a few seconds to see the new data (which is actually a reasonable way to look at this).
=> Delayed job to purge CDN data to fix race condition

app/controllers/projects_controller.rb, app/jobs/purge_cdn_project_job.rb
When purging the CDN of a particular project, we really only need its record_key, which is a simple string. So pass just that string to the job, it's more efficient.
=> Improve performance of cdn project purge job

Gemfile.lock
This updates its packaged libxml2 to v2.12.7
to resolve what we believe are false claims that we are vulnerable to CVE-2024-34459.
This is *NOT* believed to be a vulnerability in our software. Nokogiri does not provide or expose the
code that is vulnerable (which is in xmllint).
Still, updating nokogiri will get rid of a false negative, making it easier for us to detect real problems later.
=> Update nokogiri to version 1.16.5

CONTRIBUTING.md, LICENSES/CDLA-2.0, LICENSES/README.md, README.md, app/models/project.rb, app/views/projects/_form_0.html.erb, app/views/projects/_form_1.html.erb, app/views/projects/_form_2.html.erb, config/locales/en.yml, test/controllers/projects_controller_test.rb, test/fixtures/projects.yml, test/unit/lib/rake_task_test.rb
This implements the CDLA-Permissive-2.0 license for updated data.
The Linux Foundation legal team has asked us to use the CDLA-Permissive-2.0 license for newer data.
This is an *extremely* permissive license, we've noted this change with lots of warning, and it's a requirement for our legal formation.
=> Use CDLA-Permissive-2.0 for new managed data

app/controllers/application_controller.rb
Exactly which locale we go to depends on the specific browser. Therefore, we must *not* cache the result.
=> Do not cache the locale redirect

docs/best_practices_modify.py
The API modifier code never got updated for the bestpractices.dev URL change.
Signed-off-by: Tony Hansen [tony@att.com](mailto:tony@att.com)
=> Update best_practices_modify.py for bestpractices.dev

config/locales/en.yml
Many people didn't know that the best practices badge includes automation (including Eddie!). That makes sense, because it's not even noted on the front page of the active website.
This change notes, on the front page, that we have automation.
=> Note automation on the front page

Gemfile
This eliminates a warning about a jquery vulnerability. I don't think we are vulnerable at all to it, but
updating to ensure it is not crazy.
=> Update jquery-ui-rails to ~> 7.0

app/controllers/users_controller.rb, app/views/users/index.html.erb, test/controllers/users_controller_test.rb
Admins will be able to search users for name or email. This is added to better support GDPR requests.
=> Add user search for admins

app/controllers/users_controller.rb, test/controllers/users_controller_test.rb
The new admin capability for user search is primarily for GDPR requests (and similar). The previous implementation, if provided with both name and email, returned only results that met BOTH criteria (an "AND").
However, for GPDR requests, it's far more convenient to reply all users matching EITHER criteria (an "OR"). We want to ensure that we identify all possible records, even those that only partly match.
This changes user search from "AND" to "OR", to better support GDPR requests and similar.
=> Change user search to be OR instead of AND

Gemfile, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss
Remove gem jquery-ui-rails, eliminating vulnerability report https://github.com/coreinfrastructure/best-practices-badge/dependabot/73
We previously updated gem jquery-ui-rails to version 7.0.0, and had expected this to eliminate the vulnerability report. Gem version 7.0.0 was released on 2024-03-13. This is a major version number change, so we had expected it to take some extra work but for it to also eliminate the vulnerability.
However, it turns out that the vulnerability report is for versions <= 7.0.0, not < 7.0.0, as expected and as we originally thought it said. Version 7.0.0 *is* the current version of this gem as of 2024-11-27.
So we investigated our alternatives. It's likely to be unexploitable, since it only affects a checkboxradio with HTML-like initial text label. We limit …
=> Remove gem jquery-ui-rails

.circleci/config.yml
The heroku CLI has changed how it's installed. Match it.
=> Change how heroku CLI is installed in the deployer

.circleci/config.yml
Use Heroku's current recommended steps to install their CLI tool. Basically, download their installer script and run it. For more information:
https://devcenter.heroku.com/articles/heroku-cli
All programs are downloaded using https: (not http:), and we trust Heroku anyway, since they're the ones running our code.
=> Install heroku CLI using their installer

.circleci/config.yml
The "Linux" installer for heroku CLI doesn't seem to handle our container. Let's switch to the more generic installer.
=> Switch heroku installer to generic one

.circleci/config.yml
Postgres 16.4 appears to work, but before moving to it in production, we want to test against it this version. Once we switch, we want to continue to use this version for testing (until we upgrade the database version again).
=> Switch tests to use Postgres version 16.4

test/test_helper.rb
Make it simpler test the system with VCR and Google Chrome.
We don't want the system reaching out to the Internet for testing in general. The system itself should work stand alone, and we don't want its testing to interfere to with real systems. We use VCR to record & play back interactions.
However, during testing we use Google Chrome. Chrome is *notoriously* chatty and likes to update. We use Chrome-for-Testing to deal with testing (a usual approach), but it likes to download information from certain locations to handle updates.
These downloads are *not* part of the system's execution itself, and we have no permissions to write to these facilities (so we can't possibly interfere with their interactions). Thus, let's allow these test-infrastructure downloads, so that we don't have to …
=> Simplify using Google Chrome for testing via VCR

update-heroku-db
We don't need to update our database often, but when we do, it would be better to reuse an existing already-tested script for the purpose. Here's the script we've used to update the version of PostgreSQL in our production site.
=> Commit script update-heroku-db

config/locales/en.yml
While working on a company-internal fork of this project, I copied all the criteria to a Markdown document to make it easier for us to assess which criteria would need to change to suit our internal environment. My editor highlighted this unmatched parenthesis.  I'm not sure if removing it is the right thing to do, though, or if pulling the "see also" sentence into the prior parenthetical statement would be better.
=> Remove extraneous parenthesis

db/migrate/20241219131058_remove_old_yaml_object_from_versions.rb, db/schema.rb
We now use JSON to store all versions data, and have converted the existing YAML into JSON. Remove the YAML copy of the old data.
=> Remove old YAML format for versions data

config/environments/test.rb, lib/tasks/default.rake
Clean up test framework - fix deprecated way to use show_exceptions and clarify a Rakefile comment.
=> Minor test cleanup, show_exceptions and Rakefile

lib/tasks/default.rake
Modify the default 'rake' command to include 'test:all'.
Previously we patched up 'rake test' so it included system tests ('test:system'), and that meant the default rake command ran all the tests.
However, this had downsides:
1. It's harder to run just non-system tests, since "rake test" no longer does it.
2. The system tests were run separately, which mean that they weren't as well integrated into the test run.
More recent versions of Rails support "test:all" to run all tests. Let's use that, now that it's available.
=> Change default 'rake' to run test:all

app/assets/stylesheets/static_pages.scss
We have a new OpenSSF logo, but in two places we didn't update it and still showed the old logo.
This commit fixes that, so we show the new logo.
=> Update logo image

config/locales/.translation_io, config/locales/translation.de.yml, config/locales/translation.es.yml, config/locales/translation.fr.yml, config/locales/translation.ja.yml, config/locales/translation.ru.yml, config/locales/translation.sw.yml, config/locales/translation.zh-CN.yml
The translations were including special constructs to retrieve icons from Font Awesome. In retrospect, that was a mistake. They aren't translations; the icons stay the same in translations. This also makes it harder to change how icons are retrieved or which icons are used.
A previous commit inserted the icons and then the translations. However, if we don't fix the translations, in many places a user will see the icon twice (one from the app and one from the locale's translation).
This fixes the translations so that they no longer include the icons.
=> Remove icons from translations

app/controllers/projects_controller.rb, app/models/badge.rb
Two regexes weren't efficient, replace them with something that is.
This also modifies app/models/badge.rb load_svg to check its input. This was already done earlier, but static analysis tools can't easily see that. It won't hurt us to check twice, as a defense mechanism, so let's do that. Then it's *clear* we only load known-acceptable values.
=> Improve efficiency, add defensive check

app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/_form_0.html.erb, config/locales/en.yml, test/controllers/projects_controller_test.rb
Admins have been able to change project ownership.
Now owners can also change ownership. To prevent accidents, the new owner id must be entered twice. This creates more text for translation.
=> Enable owners to change project ownership

Rakefile, test/unit/lib/rake_task_test.rb
Guard against loading Rails tasks multiple times in Rakefile to prevent constant redefinition warnings during test runs. Also improve the rake task test to use bundle exec and suppress stderr output for cleaner test execution.
=> Prevent Rake task redefinition warnings

app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/controllers/static_pages_controller.rb
Add cases where cookies are set and where the external cache is not saved.  We've been trying to optimize the website by sometimes omitting cookies or aggressively caching. However, this can sometimes cause some subtle bugs.
What *really* matters is that we use the CDN caches for badge images, and that we not set cookies in that case (so that we avoid becoming a tracking cookie). *That* is what's important.
Trying to be clever about cachine other pages that vary, or not sending cookies in special cases, can lead to really complex and hard-to-debug situations.
In general, we try to take the "simple" path, let's do that with caches and cookies too.
=> Bugfix: Change external cache and cookie behavior

app/controllers/application_controller.rb, app/controllers/badge_static_controller.rb, app/controllers/projects_controller.rb, config/initializers/cache_control_fix.rb, test/integration/project_get_test.rb
Eliminate external caching of most pages. Instead, use an external cache (especially the CDN, but also the user web broswer) only for the pages that *most*
matter for performance - particularly badge images.
Before we were using some clever tricks to externally cache more pages. However, this turns out to be tricky to get right because *many* pages vary depending on who is seeing them. This includes the pages headers (which vary depending on whether or not you're logged in), the "flash" reply (which may or may not be in a cookie), and the CSRF countermeasures.
This really isn't *necessary*. Most legitimate retrievals are badge images (because that's what is embedded in READMEs), so optimizing that is enough.
For interactive use, we use fragment caching, which is built into Rails and does …
=> Greatly simplify external cache handling

app/assets/javascripts/project-form.js
The default web browser behavior when going to an anchor doesn't automatically open a named panel, and opens in the "wrong place" because it doesn't account for the navbar height (so the navbar often covers the contents). So we've long implemented some code so that when you're running client-side JavaScript it behaves in a nicer way.
The previous anchored scrolling implementation used a fixed 100px offset for the navbar. This caused incorrect scroll positioning when the navbar wrapped to multiple lines or had different heights due to various screen sizes.
Key improvements:
- Dynamically measure actual navbar height instead of using a fixed offset
- Use requestAnimationFrame so measurements occur after layout completion
- Handle all anchor navigation scenarios: initial page load, hash …
=> Improve anchored scrolling for navbar height

app/assets/stylesheets/static_pages.scss
In at least some versions of Firefox, the display of "N/A" doesn't look good, because it adds a line break after "/". This adds a tweak that solves the problem - tweak the CSS to prevent any line breaks within radio button labels (.criteria-radio label), eliminating the unhelpful word wrap.
Our radio button labels are very short, so the word wrapping was unhelpful.
This may help other browsers too, I just noticed it in Firefox.
=> Fix display of N/A on Firefox

Gemfile, Gemfile.lock
This updated gem includes integrations for Rails,
so we no longer need a separate dotenv-rails.
=> Update gem dotenv to version 3.1.8

app/controllers/application_controller.rb, app/controllers/password_resets_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/sessions_helper.rb, app/models/user.rb, config/initializers/rack_attack.rb
Claude Code identified a number of possible security issues. None are significant. However, since we want to re-run analysis later, I added many inline comments to
justify why there isn't a serious problem. That way, later AI tools (and humans!) will have the information they need to help them realize that these aren't serious security issues.
In some cases I added additional hardening. None was strictly necessary, but adding more hardening to make the software even *harder* to attack seemed like a good idea, as long as they were easy to add and didn't add a maintenance burden.
Claimed issues:
1. Race Condition in User Email Validation in `app/models/user.rb`. It's true that Rails' validation by itself has a race condition, but we *also* enforce that in the database where there can't be a …
=> Address claimed security issues from Claude Code

app/models/additional_right.rb, app/models/application_record.rb, app/models/project.rb, test/controllers/projects_controller_test.rb
Improve some model documentation.
Add to AdditionalRight a utility method `for_project` to follow usual Rails conventions a little better. Following conventions can help future developers.
=> Improve model docs, add utility method

script/report_code_statistics
Reverse order of stats so the gem up-to-date% (if printed) will logically follow, and clean up script.
=> Tweak report_code_statistics
