coreinfrastructure/best-practices-badge

criteria.md
Attempting to bring consistency of phrases, terms, and formatting to the Quality section.
I'm not familiar with the warning flags subsection so my changes may not be that accurate.
=> Edits to Quality section

criteria.md
Attempting to bring consistency of phrases, terms, and formatting to the introduction.
=> Edits to the Introduction

criteria.md
Attempting to bring consistency of phrases, terms, and formatting to the Change Control section
=> Edits to Change Control

criteria.md
Attempting to bring consistency of phrases, terms, and formatting to the OSS Project Basics section.
=> Edits to OSS Project Basics

background.md
Here's a quick summary of how I've approached my next round of editing.
=> Criteria Style

criteria.md
updated any links that can be HTTPS rather than HTTP.
=> Updated links in criteria.md to HTTPS

other.md
fixed formatting for new releases section
=> Minor formatting

other.md
Removed the crypto password storage criterion which is already in the basic/bronze badge
=> Removed existing criterion

criteria.md
updated the links and super-scripted text to reflect new 'test-policy' name
=> Updated test-policy

README.md
=> added burndown link

criteria.md
Attempting to bring consistency of phrases, terms, and formatting to the Reporting section.
Previously submitted as Pull #29
=> Updates to the Reporting section

CONTRIBUTING.md, README.md
Here's a handful of formatting changes to the root .md files (contributing and readme).  Take a look and let me know if this is what you're expecting before I move onto the other .md files.
My general process was:
1. Start a new line when there's a full stop (except where it's really close to column 0)
2. Start a new line on punctuation that's close to column 80
3. Try and keep links and urls on the same line where possible
4. Break bullet points down into new lines when they near column 80
=> Md format changes

doc/INSTALL.md, doc/implementation.md, doc/other.md
updated 3 more files to 80 col formatting.
=> Md formatting phase2

doc/background.md, doc/criteria.md, doc/other.md
updated remaining .md files to use 80 col formatting
issue #149
=> Updated .md file formatting

doc/summary.md
Hi David,
There's loads of great stuff in the criteria, but I wondered if a shorter summary might be useful in some contexts -- so I had a go at creating one.  WDYT?  Useful?
Thanks for all your work on this,
David
=> Summarize best practices criteria

doc/criteria.md
=> Update to Crypto section

doc/criteria.md
These are mostly typo fixes, but in a few places I changed British
spelling to American spelling (because the overall spelling in the
document seems to be American).
=> Fix some typos, & standardize on American spelling

README.md
=> Fixed typo/mispelling

install-badge-dev-env
Version number actually incorrect, subject to change.
=> Fixed comment re: ruby version number.

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/static_pages.scss, app/controllers/projects_controller.rb, app/views/projects/index.html.erb
* Rake output files added to .gitignore.
* Shortened search field label text.
=> Added ransack gem to all scopes, and added simple project search.

app/controllers/projects_controller.rb, app/lib/chief.rb, app/lib/detective.rb, app/lib/github_content_access.rb, app/lib/how_access_repo_files_detective.rb, test/unit/lib/chief_test.rb
#167 
instead of ours in Octokit.
* Detection done in projects_controller, since app/lib classes
can't see the session data.
* Octokit Client instance injected where it is needed via
Chief and Detective instances.
=> Detect if user logged in using Github. If so, use their token

app/models/criteria.rb, app/views/static_pages/criteria.html.erb
I'm passionate about the [Enumerable](http://ruby-doc.org/core-2.2.3/Enumerable.html) mixin.
=> Refactored Criteria

Gemfile, Gemfile.lock
@david-a-wheeler Please approve gem updates. My eslintrb patch was merged upstream.
=> Dan gem updates

app/views/static_pages/criteria.html.erb
=> Add statistics on projects to /criteria.  Fixes #314

lib/tasks/default.rake
=> Retry bundle-audit update if it fails

Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/_table.html.erb, app/views/projects/index.html.erb, config/rails_best_practices.yml, config/routes.rb, test/controllers/projects_controller_test.rb
=> Dan 317 search without ransack

app/helpers/projects_helper.rb, app/views/projects/_form.html.erb, app/views/projects/_status_chooser.html.erb
When hiding Met and NAs, hide all the horizontal rules.
=> Hide horizontal rules

app/models/project.rb, app/validators/url_validator.rb, app/views/projects/new.html.erb, test/controllers/projects_controller_test.rb
=> Modify URL handling; allow : in project/repo URLs

circle.yml, doc/dependency_decisions.yml
=> Attempted fix

app/views/projects/show.html.erb
This epitomizes Rails helpers. It's also very nice.
http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words
=> Display time_ago_in_words

install-badge-dev-env
Proposed fix for #346. Rest of commit message:
* Added needed postgresql & phantomjs packages.
* Add Postgresql user with SUPERUSER privilege for current login user.
* Switched development database detection to psql command, since rails
runner command was crashing.
=> Fixed install script for Debian/Ubuntu.

CONTRIBUTING.md
=> Improve description of how to update Ruby

Gemfile, Gemfile.lock
This removes the already initialized errors. Upstream PR at https://github.com/twitter/secureheaders/pull/258.
=> Fix errors

Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/helpers/projects_helper.rb, app/lib/chief.rb, app/lib/floss_license_detective.rb, app/lib/github_basic_detective.rb, app/lib/how_access_repo_files_detective.rb, app/lib/repo_files_examine_detective.rb, app/models/project.rb, db/seeds.rb, script/my-markdown, test/controllers/projects_controller_test.rb, test/features/github_login_test.rb, test/helpers/projects_helper_test.rb, test/mailers/report_mailer_test.rb, test/models/project_test.rb, test/test_helper.rb, test/unit/lib/floss_license_detective_test.rb, test/unit/lib/name_from_url_detective_test.rb
=> Updated Rubocop

.gitignore, install-badge-dev-env
rest of commit message:
-----------------------------------
other dnf/yum-using distros.
* Uses npm to install phantomjs, due to lack of rpm package.
* Also, made some fixes recommended by shellcheck.
=> Update installation script for success on Fedora 22, and hopefully

app/views/projects/_form.html.erb, test/controllers/projects_controller_test.rb
=> Fixes #373, incorrect URLs, and regression test

test/models/user_test.rb
This gets us to 100% model coverage.
=> Increase coverage

public/google71f0b4ac8c28162e.html
This will enable use of Google Webmaster tools. I'll share access with other admins after setting up. I'm particularly interested in using this tool to track badges in use.
=> Google verification

app/models/project.rb, test/fixtures/files/feed.atom
This converts a two SQL queries to one. See http://blog.arkency.com/2013/12/rails4-preloading/
=> eager load instead of include

install-badge-dev-env
=> Refactored script to extract helper functions and avoid repetition.

app/models/project.rb
=> Escape SQL like

app/assets/stylesheets/header.scss, app/views/layouts/_header.html.erb
remove reverse-dropdown to change back to white
=> fix for account dropdown

test/models/project_stat_test.rb, test/test_helper.rb
@david-a-wheeler This will resolve the intermittent failures until we can find a better fix upstream with VCR.
=> Temporary fix for #397

Gemfile, Gemfile.lock
=> Update gem jbuilder

criteria.yml, doc/criteria.md
=> Clarify wording of crypto_keylength. Fixes #421

config/initializers/criteria_hash.rb, criteria.yml, test/models/criteria_test.rb
=> Modify criteria.yml to include major/minor groups

app/controllers/projects_controller.rb, app/mailers/report_mailer.rb, app/views/report_mailer/in_progress.text.erb, app/views/report_mailer/passing.text.erb
=> Send email to project owner when get/lose badge. Fixes #462, #132

install-badge-dev-env
=> Updated install script for Ubuntu/Mint

app/controllers/users_controller.rb, app/views/users/new.html.erb, test/integration/users_signup_test.rb
=> Updated sign up page to resend activation link if user is unactivated

app/controllers/password_resets_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, db/migrate/20161102170815_change_email_column_type.rb, db/schema.rb, doc/implementation.md, test/fixtures/users.yml, test/mailers/user_mailer_test.rb, test/models/user_test.rb
=> Change email from string to citext

app/controllers/projects_controller.rb, app/mailers/report_mailer.rb, app/views/report_mailer/report_project_deleted.text.erb, test/controllers/projects_controller_test.rb
=> Methods and tests to send report when project deleted

app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/account_activation.text.erb, app/views/user_mailer/github_welcome.html.erb, app/views/user_mailer/github_welcome.text.erb, test/features/github_login_test.rb
This addresses the sign up part of #529. 
=> Methods and test to email GitHub user on sign up.

app/controllers/projects_controller.rb, app/mailers/report_mailer.rb, app/models/project.rb, app/views/report_mailer/email_new_project_owner.html.erb, app/views/report_mailer/email_new_project_owner.text.erb, test/controllers/projects_controller_test.rb, test/features/github_login_test.rb
This address emailing on the creation of a new project in issue #529.
=> Email Project owner when they create a new project.

app/controllers/projects_controller.rb, test/fixtures/users.yml, test/integration/password_resets_test.rb, test/integration/users_login_test.rb
I added some tests to increase code coverage.  I also removed an unused method since GitHub requires urls in project description to contain http or https.
=> Some tests and changes to increase coverage in the code.

Gemfile
=> Alphabetize Gemfile

criteria.yml
=> Clarified criteria and added some N/A options.

CONTRIBUTING.md
=> Added information about callbacks to setup and teardown methods

lib/tasks/default.rake
=> Tests of Fastly caching

config/environments/production.rb
=> Fix deprecated 'config' values in production.rb

Gemfile, Gemfile.lock, app/controllers/password_resets_controller.rb, app/controllers/projects_controller.rb, app/controllers/sessions_controller.rb, app/controllers/static_pages_controller.rb, app/controllers/users_controller.rb, app/helpers/sessions_helper.rb, app/lib/detective.rb, app/lib/github_basic_detective.rb, app/lib/hardened_sites_detective.rb, app/models/badge.rb, config/environments/production.rb, db/migrate/20150903194908_create_projects.rb, db/seeds.rb, test/controllers/password_resets_controller_test.rb, test/features/filter_test.rb, test/features/github_login_test.rb, test/features/login_test.rb, test/integration/password_resets_test.rb, test/integration/users_manipulate_project_test.rb, test/integration/users_signup_test.rb, test/models/project_test.rb, test/unit/lib/chief_test.rb
@david-a-wheeler I created a separate pull request just fixing the latest Rubocop rules.
=> Fixes for new Rubocop rules

install-badge-dev-env
=> Edit install-badge-dev-env to fix feed test failure

gen_markdown.rb, lib/tasks/default.rake
=> Updates to default.rake and gen_markdown.rm now saves to criteria.md 

app/controllers/projects_controller.rb, app/helpers/projects_helper.rb, app/models/project.rb, app/views/projects/_form.html.erb, app/views/projects/edit.html.erb, app/views/projects/show.html.erb, test/controllers/projects_controller_test.rb
=> Allow users to change http to https (and vice-versa) in repo_url.

app/models/project.rb, app/validators/text_validator.rb, app/validators/utf8_validator.rb, test/controllers/projects_controller_test.rb, test/models/project_test.rb
This address #580 and adding the necessary validator and tests for it.
=> This adds a new validator and applies it to various text fields.

app/views/static_pages/error_404.html.erb
=> More informatative 404 page

test/features/github_login_test.rb
=> Increase session_helper coverage

app/models/user.rb, app/validators/password_validator.rb, db/seeds.rb, doc/implementation.md, test/controllers/password_resets_controller_test.rb, test/integration/users_edit_test.rb, test/integration/users_signup_test.rb, test/models/user_test.rb
This implements the new password rules with a validator.
=> New Password Rules (NIST SP 800-63B) with Validator

test/integration/feed_test.rb
=> Fix test environment error in feed_test.rb

CONTRIBUTING.md, update-ruby
=> Ruby update script

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, config/initializers/monkey_patches.rb, lib/tasks/default.rake
rubocop-0.47.1 upgrade necessary coding fixes.  Addresses #586 
=> Upgrade to rubocop-0.47.1

app/views/projects/_table.html.erb
=> In projects table, changed Achieved at to Last Achieved at

app/models/criteria.rb
=> Explicitly define criterion attributes in models/criteria.rb

app/assets/stylesheets/static_pages.scss, app/controllers/projects_controller.rb, app/views/projects/_form.html.erb, test/features/login_test.rb
=> Add Save (and continue) button to the project form.

app/assets/stylesheets/static_pages.scss, app/views/projects/_status_chooser.html.erb
Refined responsive status chooser form Bootstrap and CSS for better mobile. Also had to fix radio button size to prevent buttons disappearing at some small sizes.
=> Matt status chooser html fixes

doc/other.md
The edits do not change the content of the document.
Clean up of the document, making formatting and punctuation more consistent.
Corrected spelling and formatted links.
=> Minor formatting, punctuation, spelling, and link fixes

codecov.yml
=> Add codecov.yml, so if we can't find older test coverage we can continue

app/assets/javascripts/application.js, app/assets/javascripts/criteria.js.erb, app/assets/javascripts/project-form.js, app/models/criteria.rb, app/views/projects/_status_chooser.html.erb, test/features/login_test.rb
=> Move static criteria information from DOM to JavaScript

doc/other.md
Added missed superscript text in copyright_per_file criterion.
Signed-off-by: Wang Anyu <wanganyu@huawei.com>
=> Added missed superscript text in copyright_per_file

app/views/static_pages/criteria.html.erb
Couldn't resist the chance to use my favorite obscure Enumerable method:
https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-partition
=> Minor simplification

app/views/static_pages/criteria.fr.html.erb, app/views/static_pages/home.fr.html.erb, config/locales/en.yml, config/locales/fr.yml
I left the MUST, SHOULD and SUGGESTED names in the criteria page, let me know if these should be translated as well.
=> Fix language on French home page

Gemfile, Gemfile.lock
=> Use edge mail until security fix released

app/models/project.rb, app/validators/email_validator.rb, app/validators/password_validator.rb, app/validators/text_validator.rb, app/validators/url_validator.rb, config/locales/en.yml
Note the leading space is necessary because error messages prepend the field name.
=> I18n validations

lib/tasks/default.rake
=> Use ruby one-liner instead of sed

app/controllers/users_controller.rb
This significantly reduces memory allocations.
=> When displaying user in HTML, select only project fields we need

app/controllers/static_pages_controller.rb, app/views/layouts/_header.html.erb, app/views/static_pages/locale.html.erb, config/locales/en.yml, config/routes.rb
This locale chooser always goes to the home page of the selected
locale.  We could later have it switch locales & go to the current page.
=> Add simple locale chooser

config/locales/en.yml
See incorrect escaping effect on this page: https://bestpractices.coreinfrastructure.org/signup
=> Fix incorrect escaping of quote

app/assets/javascripts/criteria.js.erb, app/models/translations.rb, test/models/translations_test.rb
This is in repsonse to @dankohn's comments in
3c4e46b3ebb3e63673b103b47c3e9fb1d9c0d944
=> Drip Singleton structure for translations model.

install-badge-dev-env
=> Install fixes for OS X

Gemfile, Gemfile.lock
=> Update gems, including mail

test/unit/i18n_test.rb
=> Add Russian to I18nTest (simple i18n smoke test)

app/views/password_resets/new.html.erb
=> Fixed a typo in the forgot-password form heading

README.md
=> Add FOSSA badge (showing that our licenses are fine)

lib/tasks/default.rake
=> Add rake task validate_hypertext_links

config/locales/en.yml
=> Add an explanation describing the /criteria table

app/views/project_stats/index.csv.erb, app/views/project_stats/index.html.erb, app/views/project_stats/index.json.jbuilder, config/locales/en.yml
This adds more statistical charts about silver and gold.
=> Show more statistics about silver and gold. Fixes #813.

app/controllers/static_pages_controller.rb, app/views/static_pages/robots.text.erb, config/routes.rb, public/robots.txt, test/controllers/static_pages_controller_test.rb, test/features/robots_contents_test.rb
=> robots.txt enables spiders in production

app/mailers/application_mailer.rb
=> Set empty PUBLIC_HOSTNAME to nil

app/assets/stylesheets/header.scss, app/assets/stylesheets/static_pages.scss, app/views/layouts/_header.html.erb
Moved the badge app logo into the left Nav and standarized styles in the
right Nav. Tested for functionality across languages.
Signed-off-by: Matthew T. Coursey <mcoursey@ida.org>
=> Reworked header navigation to be more standard Bootstrap navigation

config/locales/en.yml
=> Simplify text: change "will be able to" to "can" in two places

Gemfile.lock
=> Update transitively dependent gems, including rake

app/lib/github_basic_detective.rb, test/integration/users_manipulate_project_test.rb, test/unit/lib/chief_test.rb, test/unit/lib/github_basic_detective_test.rb, test/vcr_cassettes/unit_test_github_basic_detective.yml
This changes the way we detect names and descriptions from GitHub repos and ensures we remove emojis from the descriptions.  See discussion in #706
=> Correctly name & description (with emojis removed); Fixes #706

app/views/static_pages/home.html.erb, config/locales/en.yml
=> Add an email link to easily share with others

doc/security.md
=> Improve security documentation about authentication (login)

config/locales/en.yml, doc/other.md
=> Add more Code of Conduct examples

app/views/static_pages/home.html.erb
=> Change some social media buttons to use their logo colors. Fixes #977

test/controllers/projects_controller_test.rb, test/controllers/static_pages_controller_test.rb
Add a few more tests, in particular, check that we get
some reasonable text results within a few representative pages.
=> Add a few more tests

doc/api.md, doc/implementation.md
=> Add doc/api.md to document API, and add some info

app/controllers/users_controller.rb
Fix a highly-improbable race condition when deleting a user.
This commit puts the main logic of User#destroy within a transaction.
Otherwise, it is theoretically possible that between the test
"does the user own 0 projects" and "delete the user" someone could
add a project owned by the user being destroyed.
This problem is improbable, since only admins and that user can delete
the user or create a project owned by a user, and the race would have
to be timed perfectly.  There's nothing to be gained by the race, either;
it doesn't give anyone special privileges or break security.
However, it's trivial to put this inside a transaction, and I *really*
don't like having known race conditions (because they're irreproducible
they're notoriously hard to debug).
I put this in a nested transaction. …
=> Put User#destroy in a transaction

doc/security.md
Modify the security.md documentation (the assurance case)
to discuss how we address the "critical controls" identified in the
"Center for Internet Security (CIS) Controls" document
<https://www.cisecurity.org/controls/>.
These are a "prioritized set of actions to protect your organization
and data from known cyber attack vectors."
The controls don't map as well as one would like for our circumstance,
but it's useful to walk through them to see if we're missing anything
important.
=> Add discussion on CIS controls to security.md

app/views/project_stats/index.html.erb, config/locales/en.yml
Add more information about user accounts to the display of daily statistics.
=> Add info about users to daily /project_status

CONTRIBUTING.md, README.md, doc/design.md, doc/implementation.md, doc/requirements.md
The "implementation.md" file was getting overly big.
Split it up.
=> Split documentation into requirements/design/implementation

config/locales/en.yml
=> Update copyright date

test/controllers/static_pages_controller_test.rb
Improve the tests of the static pages controller.
This checks more conditions, and is pickier about
what is correct.
=> Enhance test/controllers/static_pages_controller_test.rb

config/environments/production.rb
Forcibly set config.action_controller.asset_host as
a hardening measure, as suggested by:
https://github.com/ankane/secure_rails
=> Hardening measure - config.action_controller.asset_host

app/views/users/show.html.erb
=> Add hypertext link to user display

app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/_table.html.erb, app/views/projects/badge.json.jbuilder, app/views/projects/feed.atom.builder, app/views/projects/index.html.erb, config/locales/en.yml, db/migrate/20180612170808_add_column_tiered_percentage_to_projects.rb, db/schema.rb, test/fixtures/files/feed.atom, test/fixtures/projects.yml, test/models/project_test.rb
=> Implement "tiered percentage" value. Fixes #1170

doc/INSTALL.md, install-badge-dev-env
=> Fix development environment install script

.circleci/config.yml
We really need to update the system gems, so force it.
=> Run gem update --system using REALLY_GEM_UPDATE_SYSTEM

config/locales/en.yml
=> Conflict -> Conduct

install-badge-dev-env
=> Update Homebrew commands

doc/compute-criteria-2019-03-07.txt
Document compute-criteria results
=> Add doc/compute-criteria-2019-03-07.txt

app/helpers/sessions_helper.rb
This is a minor optimization and cleanup.
If a user tries to edit a badge entry and is logged in via GitHub,
but is *NOT* editing a project whose repo is on GitHub, then there's
no need to ask GitHub if the user can edit the project... so don't.
This refactors some code into a new can_current_user_edit_on_github?
method, which should make can_edit? shorter and easier to understand.
=> Skip checking GitHub on non-GitHub projects

install-badge-dev-env
Update the badge install script for developers to work on newer version of ubuntu.
=> Update badge install

app/views/projects/_form_0.html.erb
=> Simplify the client-side check of SPDX license

app/views/report_mailer/report_monthly_announcement.html.erb, app/views/report_mailer/report_monthly_announcement.text.erb
In the emailed monthly report add data about 90% completion.
=> Add 90% data to emailed monthly report

.circleci/config.yml
=> Change test postgresql to 11.5

doc/INSTALL.md
=> INSTALL.md: Clearly document Chrome use

Gemfile.lock, app/controllers/account_activations_controller.rb, app/controllers/password_resets_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, config/locales/en.yml, db/migrate/20200127184707_add_login_permitted_at_to_users.rb, db/schema.rb, doc/implementation.md, test/controllers/password_resets_controller_test.rb, test/integration/password_resets_test.rb, test/integration/users_signup_test.rb, test/test_helper.rb, test/vcr_cassettes/github_login.yml
=> Delay local login after activation to counter spam

config/locales/en.yml
=> Tweak the "tell us" text

doc/security.md
We've changed how we check if a GitHub user can edit
a GitHub project. Document that in doc/security.md, since
that is security-relevant.
=> Tweak doc/security.md - modified GitHub edit check

doc/api.md
This PR includes a few changes to formatting (HTML encoding), consistency (NUMBER/NNN), and added a few links where they were relevant.
I didn't anything substantively.
=> Improve formatting of API docs

app/controllers/application_controller.rb
Use the new HTTP security header, "Permissions-Policy", to disable things
we don't need. It was formerly named "Feature-Policy" with a slightly
different syntax. For now we'll generate both headers, for users with
slightly older web browsers.
This is a security hardening header. With this header, an attacker
will have fewer client privileges even if the attacker finds a XSS or
similar attack that works in our application.
=> Add HTTP Header Permissions-Policy

app/views/criteria/index.html.erb
=> Fix missing cache entry for autofill

doc/requirements.md
=> Tweak requirements text

.circleci/config.yml
=> Add license_finder to CircleCI execution

test/integration/users_login_test.rb
=> Test that remember_me is encrypted

app/controllers/projects_controller.rb
Simplify the code by switching to a single CDN surrogate key.
We had two different CDN surrogate keys for each project,
one for the project badge SVG and one for the project badge as 1JSON.
But that doesn't make much sense. If the project data (as JSON) changes,
often the SVG will change too. So the separation creates extra work
and code for a relatively rare benefit.
Instead, use a single per-project key. That's much easier to understand.
When the project changes. then just purge that project's CDN key.
That's much clearer.
=> Simplify code: Have a single CDN surrogate key

config/initializers/translation.rb, config/locales/en.yml
=> Add Swahili as a locale

script/update-database.sh
Add new script "update-database.sh". This automates the steps
to update the Heroku database. The Heroku site documents how to do it,
but there are a *lot* of steps and it's *critical* to do them *all* in the
correct order. Automating them increases the likelihood of doing them
correctly.
This was used to update our site from PostgreSQL 11 to PostgreSQL 12
(the latest version Heroku supports).
=> script/update-database.sh: Added

lib/tasks/default.rake
Translators easily forget to change the URL prefix "/en/"
to their locale, yet it should ALWAYS be their own locale.
Automatically fix that during a translation:sync to reduce
translation errors.
=> On translation:sync fix URL locales

doc/translators.md
=> translators.md: Add info for translators

test/system/javascript_test.rb
Convert old file test/features/javascript_test.rb into a
Rails system test in file test/system/javascript_test.rb.
=> Convert test/features/javascript_test.rb

test/system/github_user_test.rb, test/vcr_cassettes/github_login.yml
=> Convert github_user_test.rb to Rails system test

app/controllers/project_stats_controller.rb
Change the "nontrivial" entry to do just 1 database request,
instead of doing separate requests for each chart line.
This also moves constants to be one-time computed constants,
instead of recomputing them each time. This doesn't save
much time, but it's misleading to recalculate constants.
=> project_stats: make nontrivial do *1* db request

app/controllers/project_stats_controller.rb
Switch to using JSON.fast_generate in the project_stats
entries when they generate JSON. The datasets we create
can't have cycles, but the default generator doesn't know that, and
it is a nontrivial effort to do safety checks for cycles.
This commit generates many JSON entries using fast_generate,
skipping the unnecessary safety check for cycles.
The project_stats endpoints often generate a lot of JSON,
so this is worth doing. A benchmark of nontrivial_projects showed
this saved an average of 173ms and caused 42K fewer allocations
(172K->130K) for just that endpoint.
=> Use JSON.fast_generate in project_stats

app/controllers/projects_controller.rb
This commit removes an N+1 query when we determine
the GitHub repos to display. We want to *not* show,
when asking the user what to create, the repos already
in the database. Originally we queried once for each repo
of the user; now we do it just once. It's not critical,
but it slightly speeds up project creation, and in general
we want to eliminate N+1 queries.
=> Remove N+1 query in GitHub repo_data

test/integration/recalc_test.rb
Simplify test using existing setup routine.
=> Slightly simplify test recalc_test.rb

doc/best_practices_modify.py
* Implement several minor tweaks to best_practices_modify.py:
- Users *must* use an option to select a base URL
(instead of having the localhost be the default)
- Error messages are now printed to standard error instead of
standard out
- The docstring of patch_project is enhanced, and
it points to write_to_project() which in most cases is what
users should use instead of patch_project().
=> Minor tweaks to best_practices_modify.py

doc/implementation.md
Add documentation on how to update the criteria
(we didn't explain how to recalculate and purge the cache before).
=> Document how to update criteria

doc/best_practices_modify.py
=> Type error, should return 3 Nones

config/locales/.translation_io, config/locales/translation.fr.yml, config/locales/translation.ja.yml
=> rake translation:sync

config/locales/.translation_io, config/locales/translation.fr.yml, config/locales/translation.ja.yml
=> translation:sync 2021-09-13

README.md
=> Add old name to README

config/locales/.translation_io, config/locales/translation.fr.yml, config/locales/translation.ja.yml
=> rake translation:sync 2022-01-08

app/views/static_pages/home.html.erb
Signed-off-by: Ry Jones <ry@linux.com>
=> Point Hyperledger link to different project

doc/implementation.md
=> Document how to block users

app/views/projects/new.html.erb
=> Allow tilde in URL on client side

.circleci/config.yml
We're having problem with this script, so provide more info
to help current and future debugging.
=> Improve CircleCI diagnostic info

.github/workflows/main.yml
=> Rework the GitHub workflow permissions

.circleci/config.yml
This will aid future debugging.
=> Increase git verbosity of ssh for deployment

.circleci/config.yml
=> Fix deploy script quoting

.circleci/config.yml
=> Set up heroku login

.circleci/config.yml
=> Fix heroku login

.circleci/config.yml
=> Actually write result to ~/.netrc

.circleci/config.yml
=> Fix "git push" to heroku

lib/tasks/default.rake
=> Refactor user search for GDPF

lib/tasks/default.rake
Add headers/footers, to simplify GDPR searches.
=> Improve search_user by surrounding its results (for GDPR)

doc/security.md
=> Remove extraneous blank lines

doc/security.md
=> Add credits to Scott Ankrum

doc/badge-vs-scorecards.md
=> Add brief scorecards/badge comparison

README.md
The JSON file looks terrible in Chrome, but it looks
great in Firefox.
=> Add OpenSSF Scorecards badge

doc/design.md
=> doc/design.md: Removing trailing space

doc/implementation.md
=> Tweak documents to test new keys

.circleci/config.yml
I noticed that the codecov isn't uploading correctly from circleci anymore.
=> use codecov orb

app/helpers/sessions_helper.rb
This reverts commit 06e62c176a4d41a973373940bfed4a488fe11c94.
=> Revert "Force domain name when redirecting (#2024)"

app/helpers/sessions_helper.rb
This reverts commit 3b682ce555343180e114233b68998483a3bc8b49.
=> Revert "Revert "Force domain name when redirecting (#2024)" (#2026)"

app/views/projects/_status_chooser.html.erb
This makes it easier for folks to deep link into the form.
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Make the status image a link

config/locales/.translation_io, config/locales/localization.pt-BR.yml
This records the change about login - people who log in using GitHub will have to re-authorize it.
=> Record results of translation:sync

app/assets/stylesheets/header.scss, app/views/static_pages/home.html.erb
Update logo on home page and top left.
=> use new logo

CONTRIBUTING.md
Explain in CONTRIBUTING.md that you can use `gh`.
=> document gh cli

Gemfile.lock
=> Update indirect dependencies

README.md
Update the OpenSSF Scorecard badge URLs.
=> Update URL for Scorecard badge

config/locales/.translation_io, config/locales/translation.de.yml, config/locales/translation.es.yml, config/locales/translation.fr.yml, config/locales/translation.ja.yml, config/locales/translation.pt-BR.yml, config/locales/translation.ru.yml, config/locales/translation.sw.yml, config/locales/translation.zh-CN.yml
This sets up translation for CDLA-Permissive-2.0 license change, as well as bringing in a few translations.
=> rake translation:sync on 2024-08-16

.circleci/config.yml, Gemfile.lock
Circle.yml had too aggressive cache settings causing gem conflicts
=> Update circle.yml to address cache issue

Gemfile.lock
This didn't get committed by accident.
=> fix gemfile.lock

Gemfile, Gemfile.lock
@david-a-wheeler based on my cursory research this should be worth a try
=> Sassc rails

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
- Update a very old url
- update to a font-awesome 5, should be backwards compatible, ruby gem (license MIT https://github.com/tomkr4l/font_awesome5_rails/blob/master/LICENSE)
=> Update font awesome and url

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/models/icon.rb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, config/locales/en.yml, docs/implementation.md
This reverts commit f6ea518ed8c9c6c61b317e61b5101c2adae7050d.
=> Attempt update font_awesome (again)

app/lib/hardened_sites_detective.rb
Improve the detective that analyzes websites:
* For 'x-frame-options' accept its CSP alternative.
* Report *specifically* what fields failed and on which websites, as otherwise it can be hard to figure out what to fix.
=> Improve hardened_sites detective

Gemfile.lock
We generally try to keep dependencies up-to-date, so here are a few updates to the latest versions of some dependencies where we have every reason to believe there will be no problems.
=> A few minor dependency updates

app/controllers/projects_controller.rb, test/controllers/projects_controller_test.rb
This adds tests of the repo_data method to better test it, including testing of a line that was never tested by the automated tests.
=> Improve tests of internal repo_data method

lib/tasks/default.rake
Modify the items in the default `rake` task so they're simpler and less verbose. This is helpful, for example, if it's being read by an assistant.
=> Clean up rake tasks - simpler and less verbose

config/initializers/terser.rb
Terser works fine on my system, but not on the staging system, because I forgot to commit its initialization file that I had on my system :-(. Let's fix that :-).
=> Commit terser initializer
